name: app-env
description: Generate .env file for an app

inputs:
  app_name:
    description: App name ('app', 'auth', etc. )
    required: true
  json_vars:
    description: 'vars as JSON'
    required: true
  json_secrets:
    description: 'secrets as JSON'
    required: true
  environment:
    description: Build target env.
    required: false
    default: 'ci'

runs:
  using: composite

  steps:
    - name: Setup env file
      id: setup
      shell: bash
      run: |
        file=./apps/${{ inputs.app_name }}/.env
        touch $file

        echo "file=$file" >> "$GITHUB_OUTPUT"

        git_short_hash="$(git log -1 --format=%h)"
        echo "git_short_hash=$git_short_hash" >> "$GITHUB_OUTPUT"

        git_commit_timestamp=$(git show -s --format=%cI HEAD)
        echo "git_commit_timestamp=$git_commit_timestamp" >> "$GITHUB_OUTPUT"

        application_version=$(git describe --tags --always)
        echo "application_version=$application_version" >> "$GITHUB_OUTPUT"

        echo "ENV_NAME=${{ inputs.environment }}" >> $file
        echo "COOKIE_DOMAIN=${{ inputs.environment == 'ci' && 'localhost' || ''}}"

    # required env. at build time for Next apps
    - if: ${{ contains(fromJSON('["app", "auth", "panier", "site"]'), inputs.app_name) }}
      shell: bash
      env:
        file: ${{ steps.setup.outputs.file }}
      run: |
        echo "NEXT_PUBLIC_GIT_SHORT_HASH=${{ steps.setup.outputs.git_short_hash }}" >> $file
        echo "NEXT_PUBLIC_GIT_COMMIT_TIMESTAMP=${{ steps.setup.outputs.git_commit_timestamp }}" >> $file
        echo "NEXT_PUBLIC_APPLICATION_VERSION=${{ steps.setup.outputs.application_version }}" >> $file
        echo "NEXT_PUBLIC_ENV_NAME=${{ inputs.environment }}" >> $file
        echo "NEXT_PUBLIC_APP_URL=${{ fromJSON(inputs.json_vars).APP_URL }}" >> $file
        echo "NEXT_PUBLIC_AUTH_URL=${{ fromJSON(inputs.json_vars).AUTH_URL }}" >> $file
        echo "NEXT_PUBLIC_PANIER_URL=${{ fromJSON(inputs.json_vars).PANIER_URL }}" >> $file
        echo "NEXT_PUBLIC_AXEPTIO_ID=${{ fromJSON(inputs.json_vars).AXEPTIO_ID }}" >> $file
        echo "NEXT_PUBLIC_CRISP_WEBSITE_ID=${{ fromJSON(inputs.json_vars).CRISP_WEBSITE_ID }}" >> $file
        echo "NEXT_PUBLIC_SENTRY_DSN=${{ fromJSON(inputs.json_vars).SENTRY_DSN }}" >> $file
        echo "NEXT_PUBLIC_POSTHOG_HOST=${{ fromJSON(inputs.json_vars).POSTHOG_HOST }}" >> $file
        echo "NEXT_PUBLIC_BACKEND_URL=${{ fromJSON(inputs.json_vars).BACKEND_URL }}" >> $file
        echo "NEXT_PUBLIC_SUPABASE_URL=${{ fromJSON(inputs.json_vars).SUPABASE_API_URL }}" >> $file
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ fromJSON(inputs.json_secrets).SUPABASE_ANON_KEY }}" >> $file

    # env. for backend
    - if: ${{ inputs.app_name == 'backend' }}
      shell: bash
      env:
        file: ${{ steps.setup.outputs.file }}
      run: |
        echo "TRAJECTOIRE_SNBC_SHEET_ID=${{ fromJSON(inputs.json_vars).TRAJECTOIRE_SNBC_SHEET_ID }}" >> $file
        echo "TRAJECTOIRE_SNBC_XLSX_ID=${{ fromJSON(inputs.json_vars).TRAJECTOIRE_SNBC_XLSX_ID }}" >> $file
        echo "TRAJECTOIRE_SNBC_RESULT_FOLDER_ID=${{ fromJSON(inputs.json_vars).TRAJECTOIRE_SNBC_RESULT_FOLDER_ID }}" >> $file
        echo "REFERENTIEL_TE_SHEET_ID=${{ fromJSON(inputs.json_vars).REFERENTIEL_TE_SHEET_ID }}" >> $file
        echo "REFERENTIEL_CAE_SHEET_ID=${{ fromJSON(inputs.json_vars).REFERENTIEL_CAE_SHEET_ID }}" >> $file
        echo "REFERENTIEL_ECI_SHEET_ID=${{ fromJSON(inputs.json_vars).REFERENTIEL_ECI_SHEET_ID }}" >> $file
        echo "INDICATEUR_DEFINITIONS_SHEET_ID=${{ fromJSON(inputs.json_vars).INDICATEUR_DEFINITIONS_SHEET_ID }}" >> $file
        echo "SUPABASE_URL=${{ fromJSON(inputs.json_vars).SUPABASE_API_URL }}" >> $file
        echo "SUPABASE_DATABASE_URL=${{ fromJSON(inputs.json_secrets).SUPABASE_DATABASE_URL }}" >> $file
        echo "SUPABASE_SERVICE_ROLE_KEY=${{ fromJSON(inputs.json_secrets).SUPABASE_SERVICE_ROLE_KEY }}" >> $file
        echo "SUPABASE_ANON_KEY=${{ fromJSON(inputs.json_secrets).SUPABASE_ANON_KEY }}" >> $file
        echo "GCLOUD_SERVICE_ACCOUNT_KEY=${{ fromJSON(inputs.json_secrets).GCLOUD_SERVICE_ACCOUNT_KEY }}" >> $file
        echo "DIRECTUS_API_KEY=${{ fromJSON(inputs.json_secrets).DIRECTUS_API_KEY }}" >> $file
        echo "BREVO_API_KEY=${{ fromJSON(inputs.json_secrets).BREVO_API_KEY }}" >> $file
        echo "QUEUE_REDIS_HOST=${{ fromJSON(inputs.json_vars).REDIS_HOST }}" >> $file
        echo "SUPABASE_JWT_SECRET=${{ fromJSON(inputs.json_secrets).SUPABASE_JWT_SECRET }}" >> $file

    # env. for automation tools
    - if: ${{ inputs.app_name == 'tools' }}
      shell: bash
      env:
        file: ${{ steps.setup.outputs.file }}
      run: |
        echo "TODO"
