-- Verify tet:retool/usage on pg

BEGIN;

select
    collectivite_id,
    code_siren_insee,
    nom,
    region_name,
    region_code,
    departement_name,
    departement_code,
    type_collectivite,
    nature_collectivite,
    population_totale,
    cot,
    niveau_label_cae,
    realise_label_cae,
    programme_label_cae,
    completude_cae,
    realise_courant_cae,
    programme_courant_cae,
    niveau_label_eci,
    realise_label_eci,
    programme_label_eci,
    completude_eci,
    realise_courant_eci,
    programme_courant_eci,
    nb_plans,
    nb_fiches,
    nb_indicateurs,
    nb_indicateurs_cae,
    nb_indicateurs_eci,
    nb_valeurs_indicateurs,
    nb_indicateurs_personnalises,
    nb_users_actifs,
    nb_admin,
    nb_ecriture,
    nb_lecture,
    admin_prenom_1,
    admin_nom_1,
    admin_fonction_1,
    admin_detail_fonction_1,
    admin_champs_intervention_1,
    admin_email_1,
    admin_telephone_1,
    admin_derniere_connexion_1,
    admin_prenom_2,
    admin_nom_2,
    admin_fonction_2,
    admin_detail_fonction_2,
    admin_champs_intervention_2,
    admin_email_2,
    admin_telephone_2,
    admin_derniere_connexion_2
from retool_stats_usages
where false;

ROLLBACK;
