### Appel l'endpoint pour obtenir les conséquences de la personnalisation
POST http://localhost:8888/personnalisation/
Content-Type: application/json

{
  "regles": [
    {
      "action_id": "eci_1.2.4",
      "regles": [
        {
          "formule": "si identite(type, syndicat) alors FAUX sinon VRAI",
          "type": "desactivation"
        }
      ]
    }
  ],
  "reponses": [
    {
      "id": "dechets_1",
      "value": "OUI"
    },
    {
      "id": "EP_1",
      "value": "EP_1_b"
    },
    {
      "id": "habitat_2",
      "value": 0.8
    }
  ],
  "identite": {
    "population": [
      "moins_de_20000",
      "moins_de_50000",
      "moins_de_100000"
    ],
    "type": [
      "commune"
    ],
    "localisation": []
  }
}
