name: pnpm-install
description: Run pnpm install with cache enabled

inputs:
  bryntum_access_token:
    description: Required to install @bryntum/scheduler package
    required: true

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: |
        pnpm config set '@bryntum:registry' 'https://npm.bryntum.com'
        pnpm config set '//npm.bryntum.com/:_authToken' "${{ inputs.bryntum_access_token }}"
        pnpm install --frozen-lockfile
