name: pnpm-install
description: Run pnpm install with cache enabled

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile
