TRUNCATE epci, 
    commune, 
    collectivite, 
    action_definition, 
    action_impact,
    action_relation, 
    action_computed_points, 
    indicateur_action,
    indicateur_valeur, 
    indicateur_definition, 
    indicateur_source_metadonnee,
    question_thematique, 
    labellisation_action_critere,
    labellisation_fichier_critere,
    labellisation_calendrier,
    labellisation.etoile_meta,
    imports.region,
    imports.departement,
    imports.commune,
    imports.banatic,
    storage.buckets,
    auth.users,
    dcp,
    private_utilisateur_droit,
    private_collectivite_membre,
    axe,
    fiche_action,
    fiche_action_axe,
    personne_tag,
    structure_tag,
    partenaire_tag
    RESTART IDENTITY CASCADE;


