import {
  PermissionOperation,
  PermissionOperationEnum,
} from './permission-operation.enum';
import { Role } from './roles/role.enum';

export const Permission: Record<Role, PermissionOperation[]> = {
  [Role.CONNECTE]: [],
  [Role.VERIFIE]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
  ],
  [Role.SUPPORT]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['COLLECTIVITES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.EDITION'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.EDITION'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.LECTURE'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['REFERENTIELS.LECTURE'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.LECTURE'],
    PermissionOperationEnum['PLANS.FICHES.IMPORT'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.LECTURE'],
    PermissionOperationEnum['INDICATEURS.TRAJECTOIRES.LECTURE'],
    PermissionOperationEnum['INDICATEURS.TRAJECTOIRES.EDITION'],
  ],
  [Role.ADEME]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.TRAJECTOIRES.LECTURE'],
    PermissionOperationEnum['INDICATEURS.TRAJECTOIRES.EDITION'],
  ],
  [Role.LECTURE]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['COLLECTIVITES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.LECTURE'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['REFERENTIELS.LECTURE'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.LECTURE'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.LECTURE'],
    PermissionOperationEnum['INDICATEURS.TRAJECTOIRES.LECTURE'],
    PermissionOperationEnum['INDICATEURS.TRAJECTOIRES.EDITION'],
  ],
  [Role.EDITION]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['COLLECTIVITES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.EDITION'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.EDITION'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['REFERENTIELS.LECTURE'],
    PermissionOperationEnum['REFERENTIELS.EDITION'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.LECTURE'],
    PermissionOperationEnum['PLANS.FICHES.EDITION'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.LECTURE'],
    PermissionOperationEnum['INDICATEURS.EDITION'],
    PermissionOperationEnum['INDICATEURS.TRAJECTOIRES.LECTURE'],
    PermissionOperationEnum['INDICATEURS.TRAJECTOIRES.EDITION'],
    PermissionOperationEnum['PLANS.EDITION'],
  ],
  [Role.ADMIN]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['COLLECTIVITES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TABLEAU-DE-BORD.EDITION'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.EDITION'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.EDITION'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['REFERENTIELS.LECTURE'],
    PermissionOperationEnum['REFERENTIELS.EDITION'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.LECTURE'],
    PermissionOperationEnum['PLANS.FICHES.EDITION'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.LECTURE'],
    PermissionOperationEnum['INDICATEURS.EDITION'],
    PermissionOperationEnum['INDICATEURS.TRAJECTOIRES.LECTURE'],
    PermissionOperationEnum['INDICATEURS.TRAJECTOIRES.EDITION'],
    PermissionOperationEnum['PLANS.EDITION'],
  ],
  [Role.AUDITEUR]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['COLLECTIVITES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.LECTURE'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['REFERENTIELS.LECTURE'],
    PermissionOperationEnum['REFERENTIELS.EDITION'],
    PermissionOperationEnum['REFERENTIELS.AUDIT'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.LECTURE'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.LECTURE'],
    PermissionOperationEnum['INDICATEURS.EDITION'],
    PermissionOperationEnum['INDICATEURS.TRAJECTOIRES.LECTURE'],
  ],
};
