const uiLabels = {
  annuler: 'Annuler',
  confirmer: 'Confirmer',
  valider: 'Valider',
  precedent: 'Précédent',
  suivant: 'Suivant',
  fermer: 'Fermer',
  rechercher: 'Rechercher',
  rechercherParMotsCles: 'Rechercher par mots-clés',
  saisirLeTexte: 'Saisir le texte',
  saisirTexteRichTextEditor:
    'Saisir le texte ou taper / pour afficher les options de mise en page',
  chargementEnCours: 'Chargement en cours...',
  pagePrecedente: 'Page précédente',
  pageSuivante: 'Page suivante',
  etape: ({ step }: { step: number }): string => `Étape ${step}`,
  supprimerTousLesFiltres: 'Supprimer tous les filtres',
  editer: 'Éditer',
  supprimer: 'Supprimer',
  creer: 'Créer',
  aucuneOptionDisponible: 'Aucune option disponible',
  autresActions: 'Autres actions',
  editerOption: "Éditer l'option",
  nomDeLOption: "Nom de l'option",
  supprimerUneOption: 'Supprimer une option',
  confirmerSuppressionOption:
    'Souhaitez-vous vraiment supprimer cette option de votre collectivité ?',
  ademeFr: 'ademe.fr',
  betaGouv: 'beta.gouv',
  accessibiliteNonConforme: 'Accessibilité : non conforme',
  mentionsLegales: 'Mentions légales',
  politiqueDesCookies: 'Politique des cookies',
  politiqueDeConfidentialite: 'Politique de confidentialité',
  conditionsGeneralesUtilisation: "Conditions générales d'utilisation",
  statistiques: 'Statistiques',
  ressources: 'Ressources',
  codeSource: 'Code source',
  feuilleDeRoute: 'Feuille de route',
  critereAtteint: 'Critère atteint',
  critereNonAtteint: 'Critère non atteint',
  statutDuCritere: 'Statut du critère',
  etiquette: 'Étiquette',
  saisirUnTitre: 'Saisir un titre',
  sansTitre: 'Sans titre',
  modifierLeTitre: 'Modifier le titre',
  caracteresSaisis: ({
    currentLength,
    maxLength,
  }: {
    currentLength: number;
    maxLength: number;
  }): string => `${currentLength} / ${maxLength} caractères`,
  questCeQueProConnect: 'Qu’est-ce que ProConnect ?',
  nouvelleFenetre: 'nouvelle fenêtre',
} as const;

export { uiLabels };
