const uiLabels = {
  annuler: "Annuler",
  confirmer: "Confirmer",
  valider: "Valider",
  precedent: "Précédent",
  suivant: "Suivant",
  fermer: "Fermer",
  rechercher: "Rechercher",
  rechercherParMotsCles: "Rechercher par mots-clés",
  chargementEnCours: "Chargement en cours...",
  pagePrecedente: "Page précédente",
  pageSuivante: "Page suivante",
  etape: ({ step }: { step: number }): string => `Étape ${step}`,
  supprimerTousLesFiltres: "Supprimer tous les filtres",
  editer: "Éditer",
  supprimer: "Supprimer",
  creer: "Créer",
  aucuneOptionDisponible: "Aucune option disponible",
  editerOption: "Éditer l'option",
  nomDeLOption: "Nom de l'option",
  supprimerUneOption: "Supprimer une option",
  confirmerSuppressionOption:
    "Souhaitez-vous vraiment supprimer cette option de votre collectivité ?",
  ademeFr: "ademe.fr",
  betaGouv: "beta.gouv",
  accessibiliteNonConforme: "Accessibilité : non conforme",
  mentionsLegales: "Mentions légales",
  politiqueDesCookies: "Politique des cookies",
  politiqueDeConfidentialite: "Politique de confidentialité",
  conditionsGeneralesUtilisation: "Conditions générales d'utilisation",
  statistiques: "Statistiques",
  ressources: "Ressources",
  codeSource: "Code source",
  feuilleDeRoute: "Feuille de route",
} as const;

export { uiLabels };
