-- Neutralise le script 98-webhooks.sql de l'image supabase/postgres, monté au
-- même chemin. Celui-ci installe pg_net et le schéma supabase_functions des
-- Database Webhooks Supabase, que le projet n'utilise pas : la base locale
-- reste sur les extensions standard de PostgreSQL (migration vers Scaleway).
