export enum BrevoLists {
  ID_LIST_BREVO_ONBOARDING_PAI = 87,
  ID_LIST_BREVO_ONBOARDING_GENERAL = 18,
  ID_LIST_BREVO_CREATION_PA = 75,
  ID_LIST_BREVO_SONDAGE_PA_1 = 76,
  ID_LIST_BREVO_SONDAGE_PA_2 = 77,
}
