import { IndicateurGridShape } from '../../../../indicateurs/valeurs/grid/indicateur-grid-shape';

export const POLLUANTS_ATMOSPHERIQUES_GRID_SHAPE: IndicateurGridShape = {
  NOx: {
    Résidentiel: 'cae_4.aa',
    Tertiaire: 'cae_4.ab',
    Agriculture: 'cae_4.ac',
    Déchets: 'cae_4.ad',
    Industrie: 'cae_4.ae',
    'Branche énergie': 'cae_4.af',
    'Transport routier': 'cae_4.ag',
    'Autres transports': 'cae_4.ah',
    Chantiers: 'cae_4.ai',
  },
  PM10: {
    Résidentiel: 'cae_4.ba',
    Tertiaire: 'cae_4.bb',
    Agriculture: 'cae_4.bc',
    Déchets: 'cae_4.bd',
    Industrie: 'cae_4.be',
    'Branche énergie': 'cae_4.bf',
    'Transport routier': 'cae_4.bg',
    'Autres transports': 'cae_4.bh',
    Chantiers: 'cae_4.bi',
  },
  'PM2.5': {
    Résidentiel: 'cae_4.ca',
    Tertiaire: 'cae_4.cb',
    Agriculture: 'cae_4.cc',
    Déchets: 'cae_4.cd',
    Industrie: 'cae_4.ce',
    'Branche énergie': 'cae_4.cf',
    'Transport routier': 'cae_4.cg',
    'Autres transports': 'cae_4.ch',
    Chantiers: 'cae_4.ci',
  },
  COVNM: {
    Résidentiel: 'cae_4.da',
    Tertiaire: 'cae_4.db',
    Agriculture: 'cae_4.dc',
    Déchets: 'cae_4.dd',
    Industrie: 'cae_4.de',
    'Branche énergie': 'cae_4.df',
    'Transport routier': 'cae_4.dg',
    'Autres transports': 'cae_4.dh',
    Chantiers: 'cae_4.di',
  },
  SO2: {
    Résidentiel: 'cae_4.ea',
    Tertiaire: 'cae_4.eb',
    Agriculture: 'cae_4.ec',
    Déchets: 'cae_4.ed',
    Industrie: 'cae_4.ee',
    'Branche énergie': 'cae_4.ef',
    'Transport routier': 'cae_4.eg',
    'Autres transports': 'cae_4.eh',
    Chantiers: 'cae_4.ei',
  },
  NH3: {
    Résidentiel: 'cae_4.fa',
    Tertiaire: 'cae_4.fb',
    Agriculture: 'cae_4.fc',
    Déchets: 'cae_4.fd',
    Industrie: 'cae_4.fe',
    'Branche énergie': 'cae_4.ff',
    'Transport routier': 'cae_4.fg',
    'Autres transports': 'cae_4.fh',
    Chantiers: 'cae_4.fi',
  },
};
