[transforms.parse]
inputs = [ "pipe"]
type = "remap"
source = '''
  .parsed_timestamp = parse_timestamp!(.timestamp, format: "%Y-%m-%dT%H:%M:%S.%fZ")
  if is_timestamp(.parsed_timestamp) {
    .time = to_unix_timestamp(.parsed_timestamp)
  } else {
    .time = to_unix_timestamp(now())
  }
  del(.parsed_timestamp)
  del(.timestamp)
  . = parse_json(slice!(.message, start: 44)) ?? .
'''

[sinks.hook]
type = "http"
inputs = ["parse"]
encoding.codec = "json"
uri = "${DATADOG_URI}"
method = "post"

[sinks.hook.request.headers]
DD-API-KEY = "${DATADOG_API_KEY}"
Content-Type = "application/json"

[api]
enabled = true
