import type { Thematique } from './thematiques';

const SOCLE: Record<string, readonly string[]> = {
  agriculture: [
    'activité agricole',
    'agriculture',
    "agriculture - augmentation des sécheresses et des besoins d'irrigation",
    'agriculture - gel tardif',
    'agriculture - érosion des sols',
    "agriculture, foresterie et écosystème - risque canicule, îlot de chaleur urbain et phénomène d' augmentation des températures",
    'agriculture, foresterie et écosystèmes',
    'agriculture, foresterie et écosystèmes - risque de sécheresse',
    'agriculture, inondations, sécheresse estivales.',
    'espaces agricoles',
    'sols',
    'viticulture',
  ],
  amenagement: [
    'aménagement',
    'aménagement / urbanisme',
    'aménagement / urbanisme (y compris grandes infrastructures, voirie)',
    'aménagement / urbanisme (y compris grandes infrastructures, voiries)',
    'aménagement /urbanisme',
    'aménagement : augmentation des inondations',
    "aménagement : augmentation des retraits-gonflement d'argile",
    'aménagement : risque de mouvement de terrains',
    'aménagement du territoire',
    'aménagement du territoire - ilôts de chaleur urbains',
    'aménagement du territoire - risque inondation',
    "aménagement du territoire - risques d'inondations accru",
    'aménagement du territoire - îlots de chaleur urbains',
    'aménagement du territoire, bâtiments (en lien avec le risque inondation)',
    'aménagement urbanisme',
    'aménagement/urbanisme',
    'aménagement/urbanisme (y.c grandes infrastructures, voirie)',
    'milieux urbains',
    'urbanisation',
    'urbanisme',
    "urbanisme / plans d'aménagement",
    "urbanisme : hausse de la pluviométrie et du risque d'inondation par ruissellement",
    'urbanisme – inondations',
    'urbanisme – retrait/gonflement des argiles',
    'urbanisme – îlots de chaleur urbain',
    'voirie',
  ],
  batiments: [
    'batiments',
    'bâtiments',
    'bâtiment',
    'habitat',
    'habitat / logement',
    'logement',
    'résidentiel',
    'résidentiel : hausse de la récurrences des phénomènes de retrait et gonflement des argiles',
    'patrimoine bâti de la collectivité',
    'tertiaire',
    'tertiaire (y compris patrimoine bâti de la collectivité)',
  ],
  biodiversite: [
    'biodiversité',
    'biodiversité (y compris milieux naturels)',
    "biodiversité (y compris milieux naturels) ; eau (approvisionnement en eau, assainissement, cours d'eau et ruissellement des eaux de pluie) ; espaces verts ; forêt, santé",
    'biodiversité (y.c milieux naturels)',
    'biodiversité / milieux naturels',
    'biodiversité et espaces naturels',
    'biodiversité et milieux naturels',
    'biodiversité, augmentation des températures',
    'biodiversité/forêt',
    'ecosystèmes',
    'erosion de la biodiversité',
    'milieux et écosystèmes',
    'milieux et écosystèmes - érosion des sols',
    'milieux naturels et biodiversité',
    'espace verts',
    'espaces verts',
  ],
  eau: [
    'approvisionnement en eau',
    'assainissement',
    "cours d'eau et ruissellement des eaux de pluie",
    'eau',
    "eau (approvisionnement en eau, assainissament, cours d'eau et ruissellement des eaux de pluie)",
    "eau (approvisionnement en eau, assainissement, cours d'eau et ruissellement des eaux de pluie",
    "eau (approvisionnement en eau, assainissement, cours d'eau et ruissellement des eaux de pluie)",
    "eau (cours d'eau et ruissellement)",
    "eau (eau, assainissement, cours d'eau et ruissellement)",
    'eau – évolution du régime de précipitations',
    'eau, risques naturels, agriculture, tourisme, santé et qualité de vie de la population',
    'eau, sécheresse',
    "eaux (approvisionnement en eau, assainissement, cours d'eau et ruissellements des eaux de pluie",
    'eaux superficielles',
    "gestion de l'eau",
    'gestion de la ressource en eau',
    'la ressource en eau',
    'ressource en eau',
    'ressource en eau (approvisionnement et risque inondation)',
    "ressource en eau - risque canicule, îlot de chaleur urbain et phénomène d' augmentation des températures",
    'ressource en eau - risque inondation',
    'ressources en eau',
    'ressources en eau - inondations (crues)',
    'ressources en eau - risque de sécheresse',
  ],
  economie: [
    'industrie',
    'industrie, établissements humains et société',
    "industrie, établissements humains et société - risque canicule, îlot de chaleur urbain et phénomène d' augmentation des températures",
    'industrie, établissements humains et société - risque inondation',
    'industrie, établissements humains et société - risque retrait / gonflement des argiles',
    'industries',
    'tourisme',
    'activités économiques',
    'economie',
    'economie locale',
    'economique',
    'les activités économiques : risque de mouvements de terrain',
    'les activités économiques : risque de retrait gonflement des argiles',
    'les activités économiques : risque de tempête',
    'les activités économiques : risque inondation',
    'les activités économiques : risque sismique',
    'économie',
  ],
  energie: [
    'approvisionnement en énergie',
    'energie',
    "gestion, production et distribution de l'énergie",
    "gestion, production et distribution de l'énergie (y compris approvisionnement en énergie)",
    "production d'énergie",
    'énergie',
  ],
  foret: [
    'foret',
    'forêt',
    'forêt / aménagement : augmentation des incendies',
    'forêts',
    'fôret',
  ],
  risque_cyclones: ['houle cyclonique', 'tempêtes, vents violents, cyclones'],
  risque_incendie_foret: [
    'aléa feu de forêts',
    'feu de forêt',
    'feux de culture',
    'feux de forêt et cultures',
    'feux de forêts',
    'feux de forêts et de broussailles',
    'forêt - augmentation de feux de forêts',
    'forêts – feux',
    'incendies',
    'risque feux de forets',
    'risque incendie des forêts',
    'risque incendies de forêts',
  ],
  risque_inondation: [
    'aléa inondations',
    'innondations',
    'inondation',
    'inondations',
    'inondations liées aux crues',
    'inondations par ruissellement',
    'inondations villes et bourgs centre - habitat urbain',
    'pluies torrentielles',
    'risque inondation',
  ],
  risque_recul_trait_cote: ['erosion côtière:'],
  risque_retrait_gonflement_argiles: [
    'aléa retrait-gonflement des argiles',
    'phénomène du "retrait gonflement des argiles"',
    'retrait gonflement des argiles',
    'retrait gonflement des argiles - bâti',
  ],
  risque_secheresse: [
    'risque de sécheresse',
    'sécheresse',
    'sécheresse des sols',
    "sécheresse et dégradation de l'état hydrique des sols",
  ],
  risque_submersion_marine: [
    'elevation du niveau de la mer (submersion)',
    'submersion marine',
    'submersions marines',
    'surcôte marine (submersion temporaire)',
  ],
  risque_vagues_chaleur: [
    'canicule',
    'canicule et îlots de chaleur en ville et bourgs centre',
    'canicules',
    'chaleur - évènements extrèmes',
    'chaleurs',
    'effet ilot de chaleur urbain',
    'fortes chaleurs',
    'ilot de chaleur urbain',
    'vagues de chaleur',
  ],
  risques_naturels: [
    'littoral',
    "littoral / inondation / ressources qualité de l'eau",
    'littoral : submersion marine, érosion du trait de cote',
    'canicules, sécheresse, innodnations',
    'coulées de boue',
    'forêt / sécheresse / risque incendie',
    'infrastructures et risques',
    'inondations coulées de boues',
    'inondations, feux de forêt',
    'montée des eaux marines, inondations, submersion',
    'mouvement de terrain',
    'mouvement de terrain sècheresse',
    'mouvements de terrain',
    'mouvements et effondrements de terrain',
    'mouvements et glissements de terrai',
    'mouvements et glissements de terrain',
    "protection des personnes et des biens face à l'intensification des risques naturels",
    'recul du trait de côte et submersion marine,',
    'risque incendie et sécheresse en forêt',
    'risque inondation et submersion marine',
    'risque naturel',
    'risques',
    'risques : tempête, inondation, mouvement de terrain, technologique',
    'risques naturels',
    'risques naturels (inondations, mouvements de terrain, canicules, gel...)',
    'risques naturels - habitat',
    'risques naturels aggravés',
    'risques naturels et phénomènes extrêmes',
    'risques naturels –habitat et urbanisme',
    'risques naturels-habitat',
    'submersion marine et érosion côtière',
    'sécheresses et gel tardif',
    'sécurité civile',
  ],
  sante: [
    'population',
    'population : surmortalité caniculaire',
    'populations',
    'risques sanitaires',
    'santé',
    'santé - augmentation des périodes de canicule / population vieillissante',
    "santé - pollution de l'air en cas de fortes chaleur",
    "santé - risque canicule, îlot de chaleur urbain et phénomène d' augmentation des températures",
    'santé - risques sanitaires',
    'santé - risques sanitaires accrus',
    "santé - risques sanitaires et maladies en lien avec la qualité de l'eau",
    'santé : hausse des températures moyennes annuelles',
    'santé : hausse des épisodes de canicule et vagues de chaleur',
    'santé des personnes',
    "santé, cours d'eau et ruissellement des eaux de pluie",
    'santé, vagues de chaleur, canicule',
  ],
  transport: [
    'infrastructures',
    'transport',
    'transport (y compris routier)',
    'transport (y.c routier)',
    'transports',
  ],
};

const COLLECTIVITE: Record<string, readonly string[]> = {
  Déchets: ['déchets'],
};

export const LIBELLES = new Map<string, Thematique>([
  ...Object.entries(SOCLE).flatMap(([code, formes]) =>
    formes.map((forme) => [forme, { code }] as const)
  ),
  ...Object.entries(COLLECTIVITE).flatMap(([label, formes]) =>
    formes.map((forme) => [forme, { label }] as const)
  ),
]);
