INSERT INTO public.action_impact (id, titre, description, ressources_externes, nb_collectivite_en_cours, nb_collectivite_realise, action_continue, niveau_complexite, fourchette_budgetaire, impact_tier) VALUES (4, 'Soutenir une agriculture et une alimentation plus durable', e'Soutenir, promouvoir et encourager des pratiques agricoles et alimentaires durables sur son territoire et sur ses territoires d’approvisionnement :

- en menant des actions visant à réduire les émissions de gaz à effet de serre, de particules et plus globalement les impacts environnementaux du secteur agricole (formation aux pratiques agro-écologiques, certification environnementale des exploitations...)
- en préservant le foncier agricole au travers des documents d’urbanisme et en accompagnant la mise en place d’espace agricoles ou jardiniers urbains ou péri-urbains (mesure 1.3.1)
- en mobilisant les acteurs du territoire, par exemple par le biais d’un PAT – projet alimentaire territorial – sur l’ensemble de la chaîne alimentaire (du producteur au consommateur, en passant par la transformation, la distribution et la restauration)
- en orientant ses actions et ses soutiens (techniques et financiers) pour accompagner des projets exemplaires en terme d’alimentation durable et les filières agricoles locales et durables
- en agissant sur sa restauration collective et ses achats alimentaires (prestations évènementielles), par le biais de la commande publique (approvisionnements durables et des proximité, sensibilisation des convives) en sensibilisant les habitants aux enjeux et aux actions à mettre en place (plus végétale et diversifiée, qualité des produits, respect de la saisonnalité, gestion durable des sols, lutte contre le gaspillage alimentaire...)', '{}', 25, 6, true, 3, 3, 2);
INSERT INTO public.action_impact (id, titre, description, ressources_externes, nb_collectivite_en_cours, nb_collectivite_realise, action_continue, niveau_complexite, fourchette_budgetaire, impact_tier) VALUES (6, 'Former tous les enfants et éleves aux enjeux climat-air-énergie et à l’éco-citoyenneté', 'Sensibiliser les enfants aux enjeux climat-air-énergie et à l’éco-citoyenneté.', '{}', 36, 40, true, 1, 1, 2);
INSERT INTO public.action_impact (id, titre, description, ressources_externes, nb_collectivite_en_cours, nb_collectivite_realise, action_continue, niveau_complexite, fourchette_budgetaire, impact_tier) VALUES (1, 'Identifier les personnes référentes sur les principaux sujets de la planification écologique', e'Les personnes référentes sur les sujets prioritaires (sur lesquels la collectivité dispose des compétences) sont identifiés et constituent une équipe projet qui échange facilement et régulièrement de façon transversale pour mener à bien les actions programmées.

Ces sujets comprennent notamment :
- Urbanisme et Aménagement
- Rénovation de l\'habitat
- Développement des énergies renouvelables
- Gestion de la politique d\'économie circulaire et des déchets
- Gestion de l\'eau
- Préservation de la biodiversité, gestion des espaces verts et renaturation
- Mobilité des agents et usagers du service public
- Bâtiments et patrimoine public
- Achats publics
- Ressources humaines
- Budget de la collectivité

Les postes vacants ou pour lesquels il n\'existe pas de référent sont clairement identifiés.', '< a href="https://librairie.ademe.fr/changement-climatique-et-energie/1748-actions-d-adaptation-au-changement-climatique-en-france-aujourd-hui.html#/44-type_de_produit-format_electronique" > Organiser sa politique de TE autour des référents en interne - ADEME < /a >', 5, 10, false, 1, 1, 2);
INSERT INTO public.action_impact (id, titre, description, ressources_externes, nb_collectivite_en_cours, nb_collectivite_realise, action_continue, niveau_complexite, fourchette_budgetaire, impact_tier) VALUES (5, 'Mettre en place une tarification incitative de l''eau', 'Influencer et modifier le comportement des usagers via la mise en place d''un prix de l’eau écologique et solidaire qui est un outil incitatif particulièrement performant pour limiter la consommation d’eau et permettre de mieux préserver la ressource en eau. Financer les compensations nécessaires aux usages excessifs.', '< a href="https://librairie.ademe.fr/cadic/1754/ademe-fiche_pyrenees-orientales-web.pdf" > Mettre en place une politique de gestion de l''eau au niveau du département - ADEME < /a > ', 0, 0, false, 1, 1, 2);
INSERT INTO public.action_impact (id, titre, description, ressources_externes, nb_collectivite_en_cours, nb_collectivite_realise, action_continue, niveau_complexite, fourchette_budgetaire, impact_tier) VALUES (2, 'Disposer d''un plan d''action d''adaptation au changement climatique', 'S''engager dans une démarche d''adaptation au changement climatique pour anticiper les impacts prévisibles du changement climatique, limiter leurs dégâts éventuels sur les activités socio-économiques et sur la nature, en intervenant sur les facteurs qui contrôlent leur ampleur (par exemple, l’urbanisation des zones à risques) et profiter des opportunités potentielles. Identifier explicitement les actions de la collecivité qui contribuent à l''adaptation au changement climatique.', '< a href="https://librairie.ademe.fr/cadic/1754/ademe-fiche_lyon-web.pdf" > Développer une culture du végétal en ville - ADEME < /a > < a href="https://librairie.ademe.fr/cadic/1754/ademe-fiche-camargue-0307-bd.pdf" > Repenser la gestion du littoral face aux aléas marins - ADEME < /a > < a href="https://librairie.ademe.fr/cadic/1754/ademe-fiche_chambagri_drome-web.pdf" > Concevoir des prairies résistantes aux sécheresses - ADEME < /a > ', 20, 30, false, 2, 1, 2);
INSERT INTO public.action_impact (id, titre, description, ressources_externes, nb_collectivite_en_cours, nb_collectivite_realise, action_continue, niveau_complexite, fourchette_budgetaire, impact_tier) VALUES (7, 'Mettre en place une comptabilité énergétique et des émissions de GES des bâtiments publics', e'Disposer d’un bilan énergétique et technique de tous les bâtiments et équipements publics significatifs, incluant des éléments sur les consommations d’énergie, les gaz à effet de serre, les énergies renouvelables, la qualité de l’air intérieur.
Limiter les besoins en chauffage / rafraichissement dans les bâtiments municipaux.', '< a href="https://aides-territoires.beta.gouv.fr/aides/8d5f-bilan-des-consommations-energetiques/" > Aides financières : Bénéficier d''un bilan des consommations énergétiques de vos bâtiments publics < /a > ', 22, 14, false, 2, 1, 1);
INSERT INTO public.action_impact (id, titre, description, ressources_externes, nb_collectivite_en_cours, nb_collectivite_realise, action_continue, niveau_complexite, fourchette_budgetaire, impact_tier) VALUES (3, 'Accompagner les particuliers pour la rénovation et la construction durable de leur logement', e'Gérer ou soutenir un ou des centre(s) de conseil (local ou régional) sur le climat, l\'air et l\'énergie à l\'intention des particuliers.
Soutenir également financièrement les travaux de rénovation du secteur résidentiel.
Fixer des objectifs de rénovation et suivre des indicateurs sur la rénovation/construction durable des bâtiments résidentiels et tertiaires sur le territoire.', '< a href="https://librairie.ademe.fr/cadic/1797/renovation-energetique-logements-etude-prix-2019.pdf" > Rénovation énergétique des logements : Etude des prix - ADEME < /a >', 120, 15, true, 2, 2, 2);
