VERSION 0.8

build:
  FROM ../../+front-deps

  COPY . ./apps/tools-automation-api

  RUN pnpm build:tools-automation-api

  SAVE ARTIFACT dist /dist AS LOCAL earthly-build/dist

docker:
  FROM ../../+prod-deps

  ARG DOCKER_IMAGE=$TOOLS_AUTOMATION_API_IMG_NAME

  ENV NODE_ENV production
  ENV PORT 3000
  ENV GIT_COMMIT_SHORT_SHA=$EARTHLY_GIT_SHORT_HASH
  ENV GIT_COMMIT_TIMESTAMP=$EARTHLY_GIT_COMMIT_TIMESTAMP
  ENV APPLICATION_VERSION=$APPLICATION_VERSION

  EXPOSE ${PORT}

  COPY +build/dist ./dist

  CMD ["node", "dist/apps/tools-automation-api/src/main.js"]
  SAVE IMAGE --push $DOCKER_IMAGE

deploy: ## Déploie le backend dans une app Koyeb existante
  ARG --required KOYEB_API_KEY
  ARG --required DEPLOYMENT_TIMESTAMP
  ARG SERVICE_NAME=$ENV_NAME-tools-autom-api ## Max 23 characters
  FROM ../../+koyeb --KOYEB_API_KEY=$KOYEB_API_KEY

  RUN ./koyeb services update $SERVICE_NAME/tools-automation-api \
    --debug \
    --docker $TOOLS_AUTOMATION_API_IMG_NAME \
    --env ENV_NAME=$ENV_NAME \
    --env DEPLOYMENT_TIMESTAMP=$DEPLOYMENT_TIMESTAMP \
    --env CRISP_TOKEN_IDENTIFIER=@CRISP_TOKEN_IDENTIFIER_$ENV_NAME \
    --env CRISP_TOKEN_KEY=@CRISP_TOKEN_KEY_$ENV_NAME \
    --env NOTION_TOKEN=@NOTION_TOKEN_$ENV_NAME \
    --env NOTION_BUG_DATABASE_ID=@NOTION_BUG_DATABASE_ID_$ENV_NAME \
    --env NOTION_BUG_EPIC_ID=@NOTION_BUG_EPIC_ID_$ENV_NAME \
    --env NOTION_BUG_TEMPLATE_ID=@NOTION_BUG_TEMPLATE_ID_$ENV_NAME \
    --env TET_API_URL=@TET_API_URL_$ENV_NAME \
    --env TET_API_TOKEN=@SUPABASE_SERVICE_ROLE_KEY_$ENV_NAME \
    --env MATTERMOST_NOTIFICATIONS_WEBHOOK_URL=@MATTERMOST_NOTIFICATIONS_WEBHOOK_URL_$ENV_NAME \
    --env EXTERNAL_SYSTEM_SECRET_MAP=@EXTERNAL_SYSTEM_SECRET_MAP_$ENV_NAME \
    --env SUPABASE_DATABASE_URL=@SUPABASE_DATABASE_URL_$ENV_NAME \
    --env QUEUE_REDIS_HOST=@QUEUE_REDIS_HOST_$ENV_NAME

test-build: ## construit une image pour exécuter les tests du backend
    FROM ../../+front-deps
    COPY . ./apps/tools-automation-api
    
    CMD pnpm run test:tools-automation-api
    SAVE IMAGE tools-automation-api-test:latest

test: ## lance les tests
    ARG network=host
    LOCALLY
    RUN earthly +test-build
    RUN docker run --rm \
        --name tools-automation-api-test_tet \
        --network $network \
        tools-automation-api-test:latest

