import {PHProvider} from './providers';
import dynamic from 'next/dynamic';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const PostHogPageView = dynamic(() => import('./PostHogPageView'), {
  ssr: false,
});

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="fr">
    <PHProvider>
      <body>
      <PostHogPageView />
      {children}
      </body>
    </PHProvider>
    </html>
  );
}
