import { CollectiviteAccessLevelEnum } from './collectivite-access-level.enum.schema';
import {
  PermissionOperation,
  PermissionOperationEnum,
} from './permission-operation.enum.schema';
import { AuditRole, Role, UserRole } from './role.enum.schema';

export const permissionsByRole: Record<Role, PermissionOperation[]> = {
  [UserRole.CONNECTE]: [],
  [UserRole.VERIFIE]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
  ],
  [UserRole.SUPPORT]: [
    // Permissions de base SUPPORT
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['COLLECTIVITES.READ'],
    PermissionOperationEnum['COLLECTIVITES.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.TABLEAU-DE-BORD.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.DOCUMENTS.CREATE'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.CREATE'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.UPDATE'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.DELETE'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ'],
    PermissionOperationEnum['INDICATEURS.VALEURS.MUTATE'],
    PermissionOperationEnum['PLANS.FICHES.BULK_UPDATE'],
    PermissionOperationEnum['PLANS.FICHES.CREATE'],
    PermissionOperationEnum['PLANS.FICHES.DELETE'],
    PermissionOperationEnum['PLANS.FICHES.UPDATE'],
    PermissionOperationEnum['PLANS.FICHES.IMPORT'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ'],
    PermissionOperationEnum['PLANS.MUTATE'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.READ'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ'],
    PermissionOperationEnum['REFERENTIELS.MUTATE'],
    PermissionOperationEnum['REFERENTIELS.DISCUSSIONS.READ'],
    PermissionOperationEnum['REFERENTIELS.DISCUSSIONS.MUTATE'],
    // Note: Les permissions ADMIN sont déjà incluses ci-dessus.
    // Le rôle SUPPORT a maintenant toutes les permissions ADMIN + les permissions spécifiques SUPPORT (MUTATE, IMPORT).
  ],
  [UserRole.ADEME]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.DISCUSSIONS.READ'],
  ],
  [CollectiviteAccessLevelEnum.LECTURE]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['COLLECTIVITES.READ'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.READ'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.READ'],
    PermissionOperationEnum['REFERENTIELS.DISCUSSIONS.READ'],
    PermissionOperationEnum['REFERENTIELS.DISCUSSIONS.MUTATE'],
  ],
  [CollectiviteAccessLevelEnum.EDITION_FICHES_INDICATEURS]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['COLLECTIVITES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.DOCUMENTS.CREATE'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ'],
    PermissionOperationEnum['PLANS.FICHES.UPDATE_PILOTED_BY_ME'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.UPDATE_PILOTED_BY_ME'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ'],
    PermissionOperationEnum['INDICATEURS.VALEURS.MUTATE_PILOTED_BY_ME'],
  ],
  [CollectiviteAccessLevelEnum.EDITION]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['COLLECTIVITES.READ'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.DOCUMENTS.CREATE'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ'],
    PermissionOperationEnum['REFERENTIELS.MUTATE'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ'],
    PermissionOperationEnum['PLANS.FICHES.CREATE'],
    PermissionOperationEnum['PLANS.FICHES.UPDATE'],
    PermissionOperationEnum['PLANS.FICHES.BULK_UPDATE'],
    PermissionOperationEnum['PLANS.FICHES.DELETE'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.CREATE'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.UPDATE'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.DELETE'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ'],
    PermissionOperationEnum['INDICATEURS.VALEURS.MUTATE'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.READ'],
    PermissionOperationEnum['PLANS.MUTATE'],
    PermissionOperationEnum['REFERENTIELS.DISCUSSIONS.READ'],
    PermissionOperationEnum['REFERENTIELS.DISCUSSIONS.MUTATE'],
  ],
  [CollectiviteAccessLevelEnum.ADMIN]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['COLLECTIVITES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TABLEAU-DE-BORD.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.DOCUMENTS.CREATE'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.CREATE'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.UPDATE'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.DELETE'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ'],
    PermissionOperationEnum['INDICATEURS.VALEURS.MUTATE'],
    PermissionOperationEnum['PLANS.FICHES.BULK_UPDATE'],
    PermissionOperationEnum['PLANS.FICHES.CREATE'],
    PermissionOperationEnum['PLANS.FICHES.DELETE'],
    PermissionOperationEnum['PLANS.FICHES.UPDATE'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.READ'],
    PermissionOperationEnum['PLANS.MUTATE'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ'],
    PermissionOperationEnum['REFERENTIELS.MUTATE'],
    PermissionOperationEnum['REFERENTIELS.DISCUSSIONS.READ'],
    PermissionOperationEnum['REFERENTIELS.DISCUSSIONS.MUTATE'],
  ],
  [AuditRole.AUDITEUR]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['COLLECTIVITES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.READ'],
    PermissionOperationEnum['COLLECTIVITES.DOCUMENTS.CREATE'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ'],
    PermissionOperationEnum['REFERENTIELS.MUTATE'],
    PermissionOperationEnum['REFERENTIELS.AUDIT'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.READ'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.CREATE'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.UPDATE'],
    PermissionOperationEnum['INDICATEURS.INDICATEURS.DELETE'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.VALEURS.READ'],
    PermissionOperationEnum['INDICATEURS.VALEURS.MUTATE'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.READ'],
    PermissionOperationEnum['REFERENTIELS.DISCUSSIONS.READ'],
    PermissionOperationEnum['REFERENTIELS.DISCUSSIONS.MUTATE'],
  ],
};
