import { PermissionOperation } from './permission-operation.enum';
import { Role } from './roles/role.enum';

export const Permission: Record<Role, PermissionOperation[]> = {
  [Role.CONNECTE]: [],
  [Role.VERIFIE]: [
    PermissionOperation.COLLECTIVITES_VISITE,
    PermissionOperation.REFERENTIELS_VISITE,
    PermissionOperation.PLANS_FICHES_VISITE,
    PermissionOperation.INDICATEURS_VISITE,
  ],
  [Role.SUPPORT]: [
    PermissionOperation.COLLECTIVITES_VISITE,
    PermissionOperation.COLLECTIVITES_LECTURE,
    PermissionOperation.COLLECTIVITES_EDITION,
    PermissionOperation.REFERENTIELS_VISITE,
    PermissionOperation.REFERENTIELS_LECTURE,
    PermissionOperation.PLANS_FICHES_VISITE,
    PermissionOperation.PLANS_FICHES_LECTURE,
    PermissionOperation.PLANS_FICHES_IMPORT,
    PermissionOperation.INDICATEURS_VISITE,
    PermissionOperation.INDICATEURS_LECTURE,
    PermissionOperation.INDICATEURS_TRAJECTOIRES_LECTURE,
    PermissionOperation.INDICATEURS_TRAJECTOIRES_EDITION,
  ],
  [Role.ADEME]: [
    PermissionOperation.COLLECTIVITES_VISITE,
    PermissionOperation.REFERENTIELS_VISITE,
    PermissionOperation.PLANS_FICHES_VISITE,
    PermissionOperation.INDICATEURS_VISITE,
    PermissionOperation.INDICATEURS_TRAJECTOIRES_LECTURE,
    PermissionOperation.INDICATEURS_TRAJECTOIRES_EDITION,
  ],
  [Role.LECTURE]: [
    PermissionOperation.COLLECTIVITES_VISITE,
    PermissionOperation.COLLECTIVITES_LECTURE,
    PermissionOperation.REFERENTIELS_VISITE,
    PermissionOperation.REFERENTIELS_LECTURE,
    PermissionOperation.PLANS_FICHES_VISITE,
    PermissionOperation.PLANS_FICHES_LECTURE,
    PermissionOperation.INDICATEURS_VISITE,
    PermissionOperation.INDICATEURS_LECTURE,
    PermissionOperation.INDICATEURS_TRAJECTOIRES_LECTURE,
    PermissionOperation.INDICATEURS_TRAJECTOIRES_EDITION,
  ],
  [Role.EDITION]: [
    PermissionOperation.COLLECTIVITES_VISITE,
    PermissionOperation.COLLECTIVITES_LECTURE,
    PermissionOperation.REFERENTIELS_VISITE,
    PermissionOperation.REFERENTIELS_LECTURE,
    PermissionOperation.REFERENTIELS_EDITION,
    PermissionOperation.PLANS_FICHES_VISITE,
    PermissionOperation.PLANS_FICHES_LECTURE,
    PermissionOperation.PLANS_FICHES_EDITION,
    PermissionOperation.INDICATEURS_VISITE,
    PermissionOperation.INDICATEURS_LECTURE,
    PermissionOperation.INDICATEURS_EDITION,
    PermissionOperation.INDICATEURS_TRAJECTOIRES_LECTURE,
    PermissionOperation.INDICATEURS_TRAJECTOIRES_EDITION,
  ],
  [Role.ADMIN]: [
    PermissionOperation.COLLECTIVITES_VISITE,
    PermissionOperation.COLLECTIVITES_LECTURE,
    PermissionOperation.COLLECTIVITES_TABLEAU_DE_BORD_EDITION,
    PermissionOperation.REFERENTIELS_VISITE,
    PermissionOperation.REFERENTIELS_LECTURE,
    PermissionOperation.REFERENTIELS_EDITION,
    PermissionOperation.PLANS_FICHES_VISITE,
    PermissionOperation.PLANS_FICHES_LECTURE,
    PermissionOperation.PLANS_FICHES_EDITION,
    PermissionOperation.INDICATEURS_VISITE,
    PermissionOperation.INDICATEURS_LECTURE,
    PermissionOperation.INDICATEURS_EDITION,
    PermissionOperation.INDICATEURS_TRAJECTOIRES_LECTURE,
    PermissionOperation.INDICATEURS_TRAJECTOIRES_EDITION,
  ],
  [Role.AUDITEUR]: [
    PermissionOperation.COLLECTIVITES_VISITE,
    PermissionOperation.COLLECTIVITES_LECTURE,
    PermissionOperation.REFERENTIELS_VISITE,
    PermissionOperation.REFERENTIELS_LECTURE,
    PermissionOperation.REFERENTIELS_EDITION,
    PermissionOperation.REFERENTIELS_AUDIT,
    PermissionOperation.PLANS_FICHES_VISITE,
    PermissionOperation.PLANS_FICHES_LECTURE,
    PermissionOperation.INDICATEURS_VISITE,
    PermissionOperation.INDICATEURS_LECTURE,
    PermissionOperation.INDICATEURS_EDITION,
    PermissionOperation.INDICATEURS_TRAJECTOIRES_LECTURE,
  ],
};
