export const levierEnumValues = [
  'Changement chaudières fioul + rénovation (résidentiel)',
  'Changement chaudières gaz + rénovation (résidentiel)',
  'Sobriété des bâtiments (résidentiel)',
  'Changement de chaudière à fioul (tertiaire)',
  'Changement de chaudière à gaz (tertiaire)',
  'Sobriété et isolation des bâtiments (tertiaire)',
  'Réduction des déplacements',
  'Covoiturage',
  'Vélo et transport en commun',
  'Véhicules électriques',
  'Efficacité et carburants décarbonés des véhicules privés',
  'Bus et cars décarbonés',
  'Fret décarboné et multimodalité',
  'Efficacité et sobriété logistique',
  'Bâtiments & Machines agricoles',
  'Elevage durable',
  'Changements de pratiques de fertilisation azotée',
  'Gestion des forêts et produits bois',
  'Pratiques stockantes',
  'Gestion des haies',
  'Gestion des prairies',
  'Sobriété foncière',
  'Production industrielle',
  'Captage de méthane dans les ISDND',
  'Prévention des déchets',
  'Valorisation matière des déchets',
  'Electricité renouvelable',
  'Biogaz',
  'Réseaux de chaleur décarbonés',
] as const;

export type Levier = (typeof levierEnumValues)[number];
