import { CategorieAction } from './categorie-action.enum';
import { LevierId } from './levier.enum';

export const POTENTIEL_SHARE_BY_LEVIER = {
  chaudieres_fioul_renovation_residentiel: {
    amenagement: 0.05,
    planification: 0.25,
    financement: 0.4,
    gouvernance: 0.1,
    exemplarite: 0.05,
    sensibilisation: 0.15,
  },
  chaudieres_gaz_renovation_residentiel: {
    amenagement: 0.05,
    planification: 0.2,
    financement: 0.4,
    gouvernance: 0.1,
    exemplarite: 0.05,
    sensibilisation: 0.2,
  },
  sobriete_batiments_residentiel: {
    amenagement: 0.05,
    planification: 0.15,
    financement: 0.1,
    gouvernance: 0.1,
    exemplarite: 0.1,
    sensibilisation: 0.5,
  },
  chaudiere_fioul_tertiaire: {
    amenagement: 0.1,
    planification: 0.3,
    financement: 0.3,
    gouvernance: 0.1,
    exemplarite: 0.15,
    sensibilisation: 0.05,
  },
  chaudiere_gaz_tertiaire: {
    amenagement: 0.1,
    planification: 0.3,
    financement: 0.3,
    gouvernance: 0.1,
    exemplarite: 0.15,
    sensibilisation: 0.05,
  },
  sobriete_isolation_batiments_tertiaire: {
    amenagement: 0.1,
    planification: 0.3,
    financement: 0.25,
    gouvernance: 0.1,
    exemplarite: 0.2,
    sensibilisation: 0.05,
  },
  reduction_deplacements: {
    amenagement: 0.2,
    planification: 0.2,
    financement: 0.1,
    gouvernance: 0.15,
    exemplarite: 0.2,
    sensibilisation: 0.15,
  },
  covoiturage: {
    amenagement: 0.35,
    planification: 0.15,
    financement: 0.15,
    gouvernance: 0.15,
    exemplarite: 0.1,
    sensibilisation: 0.1,
  },
  velo_transport_commun: {
    amenagement: 0.45,
    planification: 0.15,
    financement: 0.15,
    gouvernance: 0.1,
    exemplarite: 0.05,
    sensibilisation: 0.1,
  },
  vehicules_electriques: {
    amenagement: 0.25,
    planification: 0.15,
    financement: 0.25,
    gouvernance: 0.05,
    exemplarite: 0.15,
    sensibilisation: 0.15,
  },
  efficacite_carburants_decarbones_vehicules_prives: {
    amenagement: 0.05,
    planification: 0.25,
    financement: 0.3,
    gouvernance: 0.05,
    exemplarite: 0.05,
    sensibilisation: 0.3,
  },
  bus_cars_decarbones: {
    amenagement: 0.3,
    planification: 0.1,
    financement: 0.2,
    gouvernance: 0.15,
    exemplarite: 0.2,
    sensibilisation: 0.05,
  },
  fret_decarbone_multimodalite: {
    amenagement: 0.4,
    planification: 0.15,
    financement: 0.2,
    gouvernance: 0.2,
    exemplarite: 0,
    sensibilisation: 0.05,
  },
  efficacite_sobriete_logistique: {
    amenagement: 0.2,
    planification: 0.4,
    financement: 0,
    gouvernance: 0.3,
    exemplarite: 0,
    sensibilisation: 0.1,
  },
  batiments_machines_agricoles: {
    amenagement: 0,
    planification: 0,
    financement: 0.6,
    gouvernance: 0.3,
    exemplarite: 0,
    sensibilisation: 0.1,
  },
  elevage_durable: {
    amenagement: 0,
    planification: 0,
    financement: 0.6,
    gouvernance: 0.3,
    exemplarite: 0,
    sensibilisation: 0.1,
  },
  pratiques_fertilisation_azotee: {
    amenagement: 0,
    planification: 0,
    financement: 0,
    gouvernance: 0.75,
    exemplarite: 0,
    sensibilisation: 0.25,
  },
  gestion_forets_produits_bois: {
    amenagement: 0.15,
    planification: 0.15,
    financement: 0.25,
    gouvernance: 0.3,
    exemplarite: 0.1,
    sensibilisation: 0.05,
  },
  pratiques_stockantes: {
    amenagement: 0.1,
    planification: 0.15,
    financement: 0.35,
    gouvernance: 0.25,
    exemplarite: 0.05,
    sensibilisation: 0.1,
  },
  gestion_haies: {
    amenagement: 0.15,
    planification: 0.2,
    financement: 0.3,
    gouvernance: 0.2,
    exemplarite: 0.05,
    sensibilisation: 0.1,
  },
  gestion_prairies: {
    amenagement: 0.1,
    planification: 0.15,
    financement: 0.4,
    gouvernance: 0.25,
    exemplarite: 0,
    sensibilisation: 0.1,
  },
  sobriete_fonciere: {
    amenagement: 0.25,
    planification: 0.4,
    financement: 0.1,
    gouvernance: 0.15,
    exemplarite: 0.05,
    sensibilisation: 0.05,
  },
  production_industrielle: {
    amenagement: 0,
    planification: 0,
    financement: 0.5,
    gouvernance: 0.4,
    exemplarite: 0,
    sensibilisation: 0.1,
  },
  captage_methane_isdnd: {
    amenagement: 0.5,
    planification: 0.3,
    financement: 0.1,
    gouvernance: 0.1,
    exemplarite: 0,
    sensibilisation: 0,
  },
  prevention_dechets: {
    amenagement: 0.1,
    planification: 0.15,
    financement: 0.15,
    gouvernance: 0.15,
    exemplarite: 0.15,
    sensibilisation: 0.3,
  },
  valorisation_matiere_dechets: {
    amenagement: 0.3,
    planification: 0.2,
    financement: 0.15,
    gouvernance: 0.15,
    exemplarite: 0.1,
    sensibilisation: 0.1,
  },
  electricite_renouvelable: {
    amenagement: 0.3,
    planification: 0.25,
    financement: 0.2,
    gouvernance: 0.15,
    exemplarite: 0.1,
    sensibilisation: 0,
  },
  biogaz: {
    amenagement: 0.3,
    planification: 0.2,
    financement: 0.25,
    gouvernance: 0.2,
    exemplarite: 0.05,
    sensibilisation: 0,
  },
  reseaux_chaleur_decarbones: {
    amenagement: 0.5,
    planification: 0.15,
    financement: 0.15,
    gouvernance: 0.15,
    exemplarite: 0.05,
    sensibilisation: 0,
  },
} satisfies Record<LevierId, Record<CategorieAction, number>>;
