import { Role } from '@/backend/auth/gestion-des-droits/roles/role.enum';
import { Authorization } from '@/backend/auth/gestion-des-droits/authorization.enum';

export const Permission: Record<Role, Authorization[]> = {
  [Role.CONNECTE]: [],
  [Role.VERIFIE]: [Authorization.COLLECTIVITES_CONTENT_VISITE, Authorization.FICHES_VISITE, Authorization.INDICATEURS_VISITE],
  [Role.SUPPORT]: [
    Authorization.COLLECTIVITES_CONTENT_VISITE,
    Authorization.COLLECTIVITES_CONTENT_LECTURE,
    Authorization.REFERENTIELS_LECTURE,
    Authorization.FICHES_VISITE,
    Authorization.FICHES_LECTURE,
    Authorization.INDICATEURS_VISITE,
    Authorization.INDICATEURS_LECTURE,
    Authorization.INDICATEURS_TRAJECTOIRE_LECTURE,
  ],
  [Role.ADEME]: [
    Authorization.COLLECTIVITES_CONTENT_VISITE,
    Authorization.FICHES_VISITE,
    Authorization.INDICATEURS_VISITE,
    Authorization.INDICATEURS_TRAJECTOIRE_LECTURE,
  ],
  [Role.LECTURE]: [
    Authorization.COLLECTIVITES_CONTENT_VISITE,
    Authorization.COLLECTIVITES_CONTENT_LECTURE,
    Authorization.REFERENTIELS_LECTURE,
    Authorization.FICHES_VISITE,
    Authorization.FICHES_LECTURE,
    Authorization.INDICATEURS_VISITE,
    Authorization.INDICATEURS_LECTURE,
    Authorization.INDICATEURS_TRAJECTOIRE_LECTURE,
  ],
  [Role.EDITION]: [
    Authorization.COLLECTIVITES_CONTENT_VISITE,
    Authorization.COLLECTIVITES_CONTENT_LECTURE,
    Authorization.REFERENTIELS_LECTURE,
    Authorization.REFERENTIELS_EDITION,
    Authorization.FICHES_VISITE,
    Authorization.FICHES_LECTURE,
    Authorization.FICHES_EDITION,
    Authorization.INDICATEURS_VISITE,
    Authorization.INDICATEURS_LECTURE,
    Authorization.INDICATEURS_EDITION,
    Authorization.INDICATEURS_TRAJECTOIRE_LECTURE,
    Authorization.INDICATEURS_TRAJECTOIRE_EDITION,
  ],
  [Role.ADMIN]: [
    Authorization.COLLECTIVITES_CONTENT_VISITE,
    Authorization.COLLECTIVITES_CONTENT_LECTURE,
    Authorization.REFERENTIELS_LECTURE,
    Authorization.REFERENTIELS_EDITION,
    Authorization.FICHES_VISITE,
    Authorization.FICHES_LECTURE,
    Authorization.FICHES_EDITION,
    Authorization.INDICATEURS_VISITE,
    Authorization.INDICATEURS_LECTURE,
    Authorization.INDICATEURS_EDITION,
    Authorization.INDICATEURS_TRAJECTOIRE_LECTURE,
    Authorization.INDICATEURS_TRAJECTOIRE_EDITION,
  ],
  [Role.AUDITEUR]: [
    Authorization.COLLECTIVITES_CONTENT_VISITE,
    Authorization.COLLECTIVITES_CONTENT_LECTURE,
    Authorization.REFERENTIELS_LECTURE,
    Authorization.REFERENTIELS_EDITION,
    Authorization.FICHES_VISITE,
    Authorization.FICHES_LECTURE,
    Authorization.INDICATEURS_VISITE,
    Authorization.INDICATEURS_LECTURE,
    Authorization.INDICATEURS_EDITION,
    Authorization.INDICATEURS_TRAJECTOIRE_LECTURE,
  ],
};
