export const AI_PLAN_IMPORT_SOURCE_BUCKET = 'ai-plan-import-sources';

export const AI_PLAN_IMPORT_MAX_SOURCE_BYTES = 25 * 1024 * 1024;

export const AI_PLAN_IMPORT_MAX_UNCOMPRESSED_BYTES = 100 * 1024 * 1024;

export const AI_PLAN_IMPORT_MAX_IN_FLIGHT_JOBS = 20;

export const AI_PLAN_IMPORT_MAX_IN_FLIGHT_JOBS_PER_USER = 1;

export const AI_PLAN_IMPORT_MAX_JOBS_PER_COLLECTIVITE_PER_DAY = 10;
