insert into indicateur_definition
values (default,
        'ind0',
        'cae',
        'r',
        null,
        'Radioactivité',
        'description',
        'sv',
        true,
        null);

insert into indicateur_personnalise_definition
values (default,
        1,
        1,
        'Voltage',
        'Tension',
        'V',
        'commentaire',
        '17440546-f389-4d4f-bfdb-b0c94a1bd0f9');

insert into fiche_action
(collectivite_id,
 avancement,
 numeration,
 titre,
 description,
 structure_pilote,
 personne_referente,
 elu_referent,
 partenaires,
 budget_global,
 commentaire,
 date_fin,
 date_debut,
 action_ids,
 indicateur_ids,
 indicateur_personnalise_ids)
values (1,
        'pas_fait',
        'A0',
        'titre',
        'description',
        'pilote',
        'référente',
        'référent',
        'partenaires',
        '€',
        'commentaire',
        'fin',
        'début',
        array ['root']::action_id[],
        array ['ind0']::indicateur_id[],
        array [1]::integer[]);
