name: sqitch-local
description: Run sqitch (for local dev)

inputs:
  command:
    description: "Command to run"
    required: true
  target:
    description: "Target"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
    - ${{ inputs.target }}
