// Code generated by jtd-codegen for TypeScript v0.2.1

export interface ActionScore {
  action_id: string;
  referentiel: 'eci' | 'cae';
  collectivite_id: number;
  completed_taches_count: number;
  concernee: boolean;
  created_at: string;
  id: number;
  points: number;
  potentiel: number;
  previsionnel: number;
  referentiel_points: number;
  total_taches_count: number;
}
