/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiBackupPlugin from "strapi-backup-plugin/strapi-admin";
import reactIcons from "strapi-plugin-react-icons/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    i18n: i18N,
    "users-permissions": usersPermissions,
    "strapi-backup-plugin": strapiBackupPlugin,
    "react-icons": reactIcons,
  },
});
