# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class BusinessComputedScore(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BusinessComputedScore - a model defined in OpenAPI

        id: The id of this BusinessComputedScore.
        epci_id: The epci_id of this BusinessComputedScore.
        referentiel: The referentiel of this BusinessComputedScore.
        action_id: The action_id of this BusinessComputedScore.
        points: The points of this BusinessComputedScore.
        percentage: The percentage of this BusinessComputedScore.
        potentiel: The potentiel of this BusinessComputedScore.
    """

    # code generation should hide this id: int
    epci_id: int
    referentiel: str
    action_id: str
    points: float
    percentage: float
    potentiel: float


BusinessComputedScore.update_forward_refs()
