# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class BusinessActionStatut(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BusinessActionStatut - a model defined in OpenAPI

        epci_id: The epci_id of this BusinessActionStatut [Optional].
        referentiel: The referentiel of this BusinessActionStatut [Optional].
        action_id: The action_id of this BusinessActionStatut [Optional].
        avancement: The avancement of this BusinessActionStatut [Optional].
        concerne: The concerne of this BusinessActionStatut [Optional].
    """

    epci_id: Optional[int] = None
    referentiel: Optional[str] = None
    action_id: Optional[str] = None
    avancement: Optional[str] = None
    concerne: Optional[bool] = None

BusinessActionStatut.update_forward_refs()
