# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class BusinessEpci(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BusinessEpci - a model defined in OpenAPI

        id: The id of this BusinessEpci.
        siren: The siren of this BusinessEpci.
        nom: The nom of this BusinessEpci.
        created_at: The created_at of this BusinessEpci.
        modified_at: The modified_at of this BusinessEpci.
    """

    id: int
    siren: str
    nom: str
    created_at: str
    modified_at: str

    @validator("nom")
    def nom_max_length(cls, value):
        assert len(value) <= 300
        return value


BusinessEpci.update_forward_refs()
