# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class StoreActionStatut(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    StoreActionStatut - a model defined in OpenAPI

        id: The id of this StoreActionStatut.
        epci_id: The epci_id of this StoreActionStatut.
        modified_by: The modified_by of this StoreActionStatut.
        referentiel: The referentiel of this StoreActionStatut.
        action_id: The action_id of this StoreActionStatut.
        avancement: The avancement of this StoreActionStatut.
        concerne: The concerne of this StoreActionStatut.
        modified_at: The modified_at of this StoreActionStatut.
    """

    # should be skipped by code generation id: int
    epci_id: int
    modified_by: str
    referentiel: str
    action_id: str
    avancement: str
    concerne: bool
    # should be skipped by code generation modified_at: str


StoreActionStatut.update_forward_refs()
