# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class ViewActionStatut(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ViewActionStatut - a model defined in OpenAPI

        epci_id: The epci_id of this ViewActionStatut [Optional].
        modified_by: The modified_by of this ViewActionStatut [Optional].
        referentiel: The referentiel of this ViewActionStatut [Optional].
        action_id: The action_id of this ViewActionStatut [Optional].
        avancement: The avancement of this ViewActionStatut [Optional].
        concerne: The concerne of this ViewActionStatut [Optional].
    """

    epci_id: Optional[int] = None
    modified_by: Optional[str] = None
    referentiel: Optional[str] = None
    action_id: Optional[str] = None
    avancement: Optional[str] = None
    concerne: Optional[bool] = None


ViewActionStatut.update_forward_refs()
