# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class ViewComputedScore(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ViewComputedScore - a model defined in OpenAPI

        referentiel: The referentiel of this ViewComputedScore [Optional].
        action_id: The action_id of this ViewComputedScore [Optional].
        points: The points of this ViewComputedScore [Optional].
        percentage: The percentage of this ViewComputedScore [Optional].
        potentiel: The potentiel of this ViewComputedScore [Optional].
    """

    referentiel: Optional[str] = None
    action_id: Optional[str] = None
    points: Optional[float] = None
    percentage: Optional[float] = None
    potentiel: Optional[float] = None


ViewComputedScore.update_forward_refs()
