import type {
  AnnexeDocument,
  AxeLight,
  FicheBudget,
  FicheNote,
  FicheWithRelations,
} from '@tet/domain/plans';
import type { ActionWithScore } from '@tet/domain/referentiels';
import type { PdfIndicateurDefinition } from '../../fiche-action/external-types';
import type { FicheActionPdfExtendedProps } from '../../fiche-action/FicheActionPdf';
import type { PdfSectionKey } from '../../fiche-action/utils';

const fiche: FicheWithRelations = {
  id: 81152,
  collectiviteId: 1,
  collectiviteNom: 'Communauté de communes des Coëvrons',
  parentId: null,
  titre: '1. Animer et suivre le COT et  la démarche de transition écologique',
  description:
    "Le suivi et l'animation du COT demande des moyens humains pour :\n- mettre en œuvre l'ensemble des actions à piloter directement,\n- assurer le suivi des actions pilotées par les collègues ou d'autres acteurs,\n- animer le Comité de pilotage, assurer la mobilisation des élus\n\nSuivi annuel : vérifier l'atteinte des objectifs régulièrement pour l'ensemble des thématiques climat-air-énergie et économie circulaire à travers des indicateurs qualitatifs et quantitatifs - Actualiser annuellement le calendrier, le budget, les personnes responsables et l'état d'avancement des actions - Partager le tableau de bord au sein de l'équipe projet qui le renseigne et le fait évoluer",
  piliersEci: null,
  objectifs:
    "* Le suivi et l'animation du COT demande des moyens humains pour :\n Mettre en œuvre l'ensemble des actions à piloter directement, - assurer le suivi des actions pilotées par les collègues ou d'autres acteurs, - animer le Comité de pilotage, assurer la mobilisation des élus\n Suivi annuel : vérifier l'atteinte des objectifs régulièrement pour l'ensemble des thématiques climat-air-énergie et économie circulaire à travers des indicateurs qualitatifs et quantitatifs - Actualiser annuellement le calendrier, le budget, les personnes responsables et l'état d'avancement des actions - Partager le tableau de bord au sein de l'équipe projet qui le renseigne et le fait évoluer. Evaluation intermédiaire du PCAET",
  cibles: ['Collectivité elle-même'],
  ressources: 'Moyens humains et techniques',
  financements:
    '<p class="!text-sm !text-primary-9 font-[Marianne]">Financement</p>',
  budgetPrevisionnel: null,
  statut: 'À venir',
  priorite: 'Élevé',
  dateDebut: '2025-01-25',
  dateFin: '2026-03-18',
  ameliorationContinue: false,
  participationCitoyenne: 'pas-de-participation',
  participationCitoyenneType: 'consultation',
  tempsDeMiseEnOeuvre: null,
  majTermine: false,
  createdAt: '2025-12-04T10:00:00.000Z',
  createdBy: null,
  modifiedAt: '2026-04-16T14:30:00.000Z',
  modifiedBy: { id: 'user-modifier-1', prenom: 'Doe', nom: 'John' },
  restreint: false,
  thematiques: [
    { id: 1, nom: 'Énergie et climat' },
    { id: 2, nom: 'Agriculture et alimentation' },
  ],
  sousThematiques: [
    { id: 10, nom: 'Production agricole et foncier', thematiqueId: 2 },
    { id: 11, nom: 'Précarité et aide alimentaire', thematiqueId: 2 },
  ],
  libreTags: [
    { id: 100, nom: 'CAE' },
    { id: 101, nom: 'COT' },
  ],
  instanceGouvernance: [{ id: 200, nom: 'COPIL COT' }],
  pilotes: [
    {
      nom: 'Sophie Boiché',
      tagId: 1,
      userId: null,
      collectiviteId: 1,
      prenom: null,
      nomFamille: null,
      email: null,
      telephone: null,
    },
    {
      nom: 'test audrey',
      tagId: 2,
      userId: null,
      collectiviteId: 1,
      prenom: null,
      nomFamille: null,
      email: null,
      telephone: null,
    },
    {
      nom: 'Sophie Durand',
      tagId: 3,
      userId: null,
      collectiviteId: 1,
      prenom: null,
      nomFamille: null,
      email: null,
      telephone: null,
    },
    {
      nom: 'Benjamin Goullard',
      tagId: 4,
      userId: null,
      collectiviteId: 1,
      prenom: null,
      nomFamille: null,
      email: null,
      telephone: null,
    },
  ],
  services: [{ id: 300, nom: 'Direction environnement', collectiviteId: 1 }],
  structures: [{ id: 400, nom: 'Communauté de communes des Coëvrons' }],
  referents: [
    {
      nom: 'Nicolas VALLEE',
      tagId: 5,
      userId: null,
      collectiviteId: 1,
      prenom: null,
      nomFamille: null,
      email: null,
      telephone: null,
    },
  ],
  partenaires: [{ id: 500, nom: 'Acteurs du bâtiment' }],
  financeurs: [
    {
      ficheId: 81152,
      montantTtc: 10000,
      financeurTagId: 600,
      financeurTag: { id: 600, nom: 'ACTEE', collectiviteId: 1 },
    },
  ],
  effetsAttendus: [
    { id: 700, nom: 'Adaptation au changement climatique', notice: null },
    { id: 701, nom: "Allongement de la durée d'usage", notice: null },
  ],
  axes: null,
  plans: [
    {
      id: 10,
      nom: "3. Plan d'action ECi (T.E.T.E)",
      collectiviteId: 1,
      type: null,
    },
    { id: 11, nom: 'PLPDMA', collectiviteId: 1, type: null },
    { id: 12, nom: '1. Plan Climat (PCAET)', collectiviteId: 1, type: null },
  ],
  indicateurs: [
    { id: 1, nom: 'Émissions de gaz à effet de serre', unite: 'kteq CO2' },
    {
      id: 2,
      nom: 'Emissions de gaz à effet de serre totales nettes',
      unite: 'kteq CO2',
    },
    { id: 3, nom: 'Part modale - Vélos', unite: '%' },
    { id: 4, nom: 'Recyclage des déchets organiques', unite: '%' },
  ],
  etapes: null,
  notes: null,
  mesures: [
    {
      id: 'cae_1.3.1.6',
      identifiant: '1.3.1.6',
      nom: "Suivre des indicateurs relatifs à l'urbanisme durable et atteindre les objectifs fixés",
      referentiel: 'cae',
    },
    {
      id: 'cae_2.1.2',
      identifiant: '2.1.2',
      nom: 'Elaborer une stratégie patrimoniale incluant un programme de rénovation',
      referentiel: 'cae',
    },
    {
      id: 'eci_2.1',
      identifiant: '2.1',
      nom: "Disposer d'un programme de prévention des déchets",
      referentiel: 'eci',
    },
  ],
  fichesLiees: [
    { id: 81153, nom: 'Action 1.2 - Promotion du jardinage au naturel' },
    {
      id: 81154,
      nom: "Action 3.4 : Préserver les sols et les milieux favorables au bon déroulement du cycle de l'eau",
    },
    {
      id: 81155,
      nom: "Action 1.5 : Anticiper l'évolution de la ressource en eau potable en quantité et en qualité",
    },
    { id: 81156, nom: '5. Mobiliser les élus' },
  ],
  docs: [
    {
      id: 1,
      filename: 'Collectivité Démo (PA) - Indicateurs - 2026-02-19.xlsx',
    },
  ],
  budgets: null,
  sharedWithCollectivites: null,
  actionImpactId: null,
  completion: {
    ficheId: 81152,
    fields: [
      { field: 'titre', isCompleted: true },
      { field: 'description', isCompleted: true },
      { field: 'statut', isCompleted: true },
      { field: 'pilotes', isCompleted: true },
    ],
    isCompleted: true,
  },
};

const chemins: AxeLight[][] = [
  [
    {
      collectiviteId: 1,
      createdAt: '2025-01-01T00:00:00.000Z',
      id: 10,
      modifiedAt: '2025-01-01T00:00:00.000Z',
      modifiedBy: null,
      nom: "3. Plan d'action ECi (T.E.T.E)",
      panierId: null,
      parent: null,
      plan: null,
      typeId: null,
      description: null,
    },
    {
      collectiviteId: 1,
      createdAt: '2025-01-01T00:00:00.000Z',
      id: 20,
      modifiedAt: '2025-01-01T00:00:00.000Z',
      modifiedBy: null,
      nom: '3. Promouvoir la consommation responsable sur le territoire',
      panierId: null,
      parent: 10,
      plan: 10,
      typeId: null,
      description: null,
    },
  ],
  [
    {
      collectiviteId: 1,
      createdAt: '2025-01-01T00:00:00.000Z',
      id: 11,
      modifiedAt: '2025-01-01T00:00:00.000Z',
      modifiedBy: null,
      nom: 'PLPDMA',
      panierId: null,
      parent: null,
      plan: null,
      typeId: null,
      description: null,
    },
    {
      collectiviteId: 1,
      createdAt: '2025-01-01T00:00:00.000Z',
      id: 21,
      modifiedAt: '2025-01-01T00:00:00.000Z',
      modifiedBy: null,
      nom: 'Axe 3 : Promotion du réemploi',
      panierId: null,
      parent: 11,
      plan: 11,
      typeId: null,
      description: null,
    },
  ],
  [
    {
      collectiviteId: 1,
      createdAt: '2025-01-01T00:00:00.000Z',
      id: 12,
      modifiedAt: '2025-01-01T00:00:00.000Z',
      modifiedBy: null,
      nom: '1. Plan Climat (PCAET)',
      panierId: null,
      parent: null,
      plan: null,
      typeId: null,
      description: null,
    },
    {
      collectiviteId: 1,
      createdAt: '2025-01-01T00:00:00.000Z',
      id: 30,
      modifiedAt: '2025-01-01T00:00:00.000Z',
      modifiedBy: null,
      nom: "Axe 1 – Inscrire nos collectivités locales dans une démarche d'exemplarité",
      panierId: null,
      parent: 12,
      plan: 12,
      typeId: null,
      description: null,
    },
  ],
];

const sections: PdfSectionKey[] = [
  'intro',
  'acteurs',
  'indicateurs',
  'notes',
  'moyens',
  'fiches',
  'actionsLiees',
  'documents',
];

const indicateursListe: PdfIndicateurDefinition[] = [
  {
    id: 1,
    titre: 'Émissions de gaz à effet de serre',
    unite: 'kteq CO2',
    participationScore: false,
    estPerso: false,
    hasOpenData: true,
  },
  {
    id: 2,
    titre: 'Emissions de gaz à effet de serre totales nettes',
    unite: 'kteq CO2',
    participationScore: false,
    estPerso: false,
    hasOpenData: false,
  },
  {
    id: 3,
    titre: 'Part modale - Vélos',
    unite: '%',
    participationScore: false,
    estPerso: false,
    hasOpenData: true,
  },
  {
    id: 4,
    titre: 'Recyclage des déchets organiques',
    unite: '%',
    participationScore: false,
    estPerso: false,
    hasOpenData: true,
  },
];

const fichesLiees: FicheWithRelations[] = [
  {
    id: 81153,
    collectiviteId: 1,
    collectiviteNom: null,
    parentId: null,
    titre: 'Action 1.2 - Promotion du jardinage au naturel',
    description: null,
    piliersEci: null,
    objectifs: null,
    cibles: null,
    ressources: null,
    financements: null,
    budgetPrevisionnel: null,
    statut: 'En cours',
    priorite: null,
    dateDebut: null,
    dateFin: null,
    ameliorationContinue: false,
    participationCitoyenne: null,
    participationCitoyenneType: null,
    tempsDeMiseEnOeuvre: null,
    majTermine: null,
    createdAt: '2025-06-01T00:00:00.000Z',
    createdBy: null,
    modifiedAt: '2026-04-02T00:00:00.000Z',
    modifiedBy: null,
    restreint: false,
    thematiques: null,
    sousThematiques: null,
    libreTags: null,
    instanceGouvernance: null,
    pilotes: null,
    services: null,
    structures: null,
    referents: null,
    partenaires: null,
    financeurs: null,
    effetsAttendus: null,
    axes: null,
    plans: [{ id: 11, nom: 'PLPDMA', collectiviteId: 1, type: null }],
    indicateurs: null,
    etapes: null,
    notes: null,
    mesures: null,
    fichesLiees: null,
    docs: null,
    budgets: null,
    sharedWithCollectivites: null,
    actionImpactId: null,
    completion: { ficheId: 81153, fields: [], isCompleted: false },
  },
  {
    id: 81154,
    collectiviteId: 1,
    collectiviteNom: null,
    parentId: null,
    titre:
      "Action 3.4 : Préserver les sols et les milieux favorables au bon déroulement du cycle de l'eau",
    description: null,
    piliersEci: null,
    objectifs: null,
    cibles: null,
    ressources: null,
    financements: null,
    budgetPrevisionnel: null,
    statut: 'En cours',
    priorite: 'Élevé',
    dateDebut: null,
    dateFin: '2025-12-31',
    ameliorationContinue: false,
    participationCitoyenne: null,
    participationCitoyenneType: null,
    tempsDeMiseEnOeuvre: null,
    majTermine: null,
    createdAt: '2025-07-01T00:00:00.000Z',
    createdBy: null,
    modifiedAt: '2026-02-19T00:00:00.000Z',
    modifiedBy: null,
    restreint: false,
    thematiques: null,
    sousThematiques: null,
    libreTags: null,
    instanceGouvernance: null,
    pilotes: [
      {
        nom: 'Benjamin Goullard',
        tagId: 4,
        userId: null,
        collectiviteId: 1,
        prenom: null,
        nomFamille: null,
        email: null,
        telephone: null,
      },
    ],
    services: null,
    structures: null,
    referents: null,
    partenaires: null,
    financeurs: null,
    effetsAttendus: null,
    axes: null,
    plans: [
      { id: 12, nom: '1. Plan Climat (PCAET)', collectiviteId: 1, type: null },
    ],
    indicateurs: null,
    etapes: null,
    notes: null,
    mesures: null,
    fichesLiees: null,
    docs: null,
    budgets: null,
    sharedWithCollectivites: null,
    actionImpactId: null,
    completion: { ficheId: 81154, fields: [], isCompleted: false },
  },
  {
    id: 81155,
    collectiviteId: 1,
    collectiviteNom: null,
    parentId: null,
    titre:
      "Action 1.5 : Anticiper l'évolution de la ressource en eau potable en quantité et en qualité",
    description: null,
    piliersEci: null,
    objectifs: null,
    cibles: null,
    ressources: null,
    financements: null,
    budgetPrevisionnel: null,
    statut: 'En cours',
    priorite: 'Bas',
    dateDebut: null,
    dateFin: null,
    ameliorationContinue: false,
    participationCitoyenne: null,
    participationCitoyenneType: null,
    tempsDeMiseEnOeuvre: null,
    majTermine: null,
    createdAt: '2025-08-01T00:00:00.000Z',
    createdBy: null,
    modifiedAt: '2026-02-19T00:00:00.000Z',
    modifiedBy: null,
    restreint: false,
    thematiques: null,
    sousThematiques: null,
    libreTags: null,
    instanceGouvernance: null,
    pilotes: [
      {
        nom: 'Benjamin Goullard',
        tagId: 4,
        userId: null,
        collectiviteId: 1,
        prenom: null,
        nomFamille: null,
        email: null,
        telephone: null,
      },
    ],
    services: [{ id: 301, nom: 'Service Déchets', collectiviteId: 1 }],
    structures: null,
    referents: null,
    partenaires: null,
    financeurs: null,
    effetsAttendus: null,
    axes: null,
    plans: [
      { id: 12, nom: '1. Plan Climat (PCAET)', collectiviteId: 1, type: null },
    ],
    indicateurs: null,
    etapes: null,
    notes: null,
    mesures: null,
    fichesLiees: null,
    docs: null,
    budgets: null,
    sharedWithCollectivites: null,
    actionImpactId: null,
    completion: { ficheId: 81155, fields: [], isCompleted: false },
  },
  {
    id: 81156,
    collectiviteId: 1,
    collectiviteNom: null,
    parentId: null,
    titre: '5. Mobiliser les élus',
    description: null,
    piliersEci: null,
    objectifs: null,
    cibles: null,
    ressources: null,
    financements: null,
    budgetPrevisionnel: null,
    statut: 'En cours',
    priorite: null,
    dateDebut: null,
    dateFin: null,
    ameliorationContinue: false,
    participationCitoyenne: null,
    participationCitoyenneType: null,
    tempsDeMiseEnOeuvre: null,
    majTermine: null,
    createdAt: '2025-09-01T00:00:00.000Z',
    createdBy: null,
    modifiedAt: '2026-03-10T00:00:00.000Z',
    modifiedBy: null,
    restreint: false,
    thematiques: null,
    sousThematiques: null,
    libreTags: null,
    instanceGouvernance: null,
    pilotes: [
      {
        nom: 'Aurore Grandvuinet',
        tagId: 6,
        userId: null,
        collectiviteId: 1,
        prenom: null,
        nomFamille: null,
        email: null,
        telephone: null,
      },
    ],
    services: null,
    structures: null,
    referents: null,
    partenaires: null,
    financeurs: null,
    effetsAttendus: null,
    axes: null,
    plans: [
      { id: 13, nom: '2. Plan CAE (COT)', collectiviteId: 1, type: null },
    ],
    indicateurs: null,
    etapes: null,
    notes: null,
    mesures: null,
    fichesLiees: null,
    docs: null,
    budgets: null,
    sharedWithCollectivites: null,
    actionImpactId: null,
    completion: { ficheId: 81156, fields: [], isCompleted: false },
  },
];

const actionsLiees: ActionWithScore[] = [
  {
    actionId: 'cae_1.3.1.6',
    referentiel: 'cae',
    referentielId: 'cae',
    referentielVersion: '2024-01-01',
    identifiant: '1.3.1.6',
    nom: "Suivre des indicateurs relatifs à l'urbanisme durable et atteindre les objectifs fixés",
    description: '',
    contexte: '',
    exemples: '',
    ressources: '',
    reductionPotentiel: '',
    perimetreEvaluation: '',
    preuve: null,
    points: 1.8,
    pourcentage: null,
    categorie: null,
    exprScore: null,
    modifiedAt: '2025-01-01T00:00:00.000Z',
    pilotes: [],
    services: [],
    statut: 'non_renseigne',
    desactive: false,
    concerne: true,
    depth: 4,
    score: {
      actionId: 'cae_1.3.1.6',
      pointReferentiel: 1.8,
      pointPotentiel: 1.8,
      pointPotentielPerso: null,
      pointFait: 0,
      pointPasFait: 0,
      pointProgramme: 0,
      pointNonRenseigne: 1.8,
      totalTachesCount: 2,
      completedTachesCount: 0,
      faitTachesAvancement: 0,
      programmeTachesAvancement: 0,
      pasFaitTachesAvancement: 0,
      pasConcerneTachesAvancement: 0,
      concerne: true,
      desactive: false,
      renseigne: false,
      avancement: 'non_renseigne',
    },
  },
  {
    actionId: 'cae_2.1.2',
    referentiel: 'cae',
    referentielId: 'cae',
    referentielVersion: '2024-01-01',
    identifiant: '2.1.2',
    nom: 'Elaborer une stratégie patrimoniale incluant un programme de rénovation',
    description: '',
    contexte: '',
    exemples: '',
    ressources: '',
    reductionPotentiel: '',
    perimetreEvaluation: '',
    preuve: null,
    points: 8,
    pourcentage: null,
    categorie: null,
    exprScore: null,
    modifiedAt: '2025-01-01T00:00:00.000Z',
    pilotes: [],
    services: [],
    statut: 'detaille',
    desactive: false,
    concerne: true,
    depth: 3,
    score: {
      actionId: 'cae_2.1.2',
      pointReferentiel: 8,
      pointPotentiel: 8,
      pointPotentielPerso: null,
      pointFait: 4.1,
      pointPasFait: 0,
      pointProgramme: 3.9,
      pointNonRenseigne: 0,
      totalTachesCount: 5,
      completedTachesCount: 5,
      faitTachesAvancement: 2,
      programmeTachesAvancement: 3,
      pasFaitTachesAvancement: 0,
      pasConcerneTachesAvancement: 0,
      concerne: true,
      desactive: false,
      renseigne: true,
      avancement: 'detaille',
    },
  },
  {
    actionId: 'eci_2.1',
    referentiel: 'eci',
    referentielId: 'eci',
    referentielVersion: '2024-01-01',
    identifiant: '2.1',
    nom: "Disposer d'un programme de prévention des déchets",
    description: '',
    contexte: '',
    exemples: '',
    ressources: '',
    reductionPotentiel: '',
    perimetreEvaluation: '',
    preuve: null,
    points: 0,
    pourcentage: null,
    categorie: null,
    exprScore: null,
    modifiedAt: '2025-01-01T00:00:00.000Z',
    pilotes: [],
    services: [],
    statut: 'non_renseigne',
    desactive: false,
    concerne: true,
    depth: 2,
    score: {
      actionId: 'eci_2.1',
      pointReferentiel: 0,
      pointPotentiel: 0,
      pointPotentielPerso: null,
      pointFait: 0,
      pointPasFait: 0,
      pointProgramme: 0,
      pointNonRenseigne: 0,
      totalTachesCount: 0,
      completedTachesCount: 0,
      faitTachesAvancement: 0,
      programmeTachesAvancement: 0,
      pasFaitTachesAvancement: 0,
      pasConcerneTachesAvancement: 0,
      concerne: true,
      desactive: false,
      renseigne: false,
      avancement: 'non_renseigne',
    },
  },
];

const annexes: AnnexeDocument[] = [
  {
    id: 1,
    collectiviteId: 1,
    ficheId: 81152,
    modifiedAt: '2026-02-19T09:00:00.000Z',
    modifiedByNom: 'Sophie Boiché',
    commentaire: null,
    fichier: {
      filename: 'Collectivité Démo (PA) - Indicateurs - 2026-02-19.xlsx',
      confidentiel: false,
      hash: 'fixture-hash-annexe-1',
      bucketId: 'fixture-bucket-1',
      filesize: 120000,
    },
    lien: null,
  },
];

const notes: FicheNote[] = [
  {
    id: 1,
    dateNote: '2026-04-03',
    note: 'Suite à la réunion : un arbitrage budget est attendu pour 2027.',
    createdAt: '2026-04-03T10:00:00.000Z',
    modifiedAt: '2026-04-03T10:00:00.000Z',
    createdBy: {
      id: 'user-note-1',
      prenom: 'Manon',
      nom: 'Bouvier',
    },
    modifiedBy: {
      id: 'user-note-1',
      prenom: 'Manon',
      nom: 'Bouvier',
    },
  },
  {
    id: 2,
    dateNote: '2026-02-23',
    note: "Cotech : L'action a bien évolué depuis son lancement. On peut noter une adoption du pilotage par plus de 50% des membres de l'équipe.",
    createdAt: '2026-02-23T14:00:00.000Z',
    modifiedAt: '2026-04-03T09:00:00.000Z',
    createdBy: {
      id: 'user-note-2',
      prenom: 'test',
      nom: 'audrey',
    },
    modifiedBy: {
      id: 'user-note-1',
      prenom: 'Manon',
      nom: 'Bouvier',
    },
  },
];

const budgets: FicheBudget[] = [
  {
    id: 1,
    ficheId: 81152,
    type: 'investissement',
    unite: 'HT',
    annee: null,
    budgetPrevisionnel: 10000,
    budgetReel: 5000,
  },
  {
    id: 3,
    ficheId: 81152,
    type: 'fonctionnement',
    unite: 'HT',
    annee: 2025,
    budgetPrevisionnel: 15000,
    budgetReel: 20000,
  },
  {
    id: 4,
    ficheId: 81152,
    type: 'fonctionnement',
    unite: 'HT',
    annee: 2026,
    budgetPrevisionnel: 20000,
    budgetReel: 25000,
  },
];

export const ficheActionFixture: FicheActionPdfExtendedProps = {
  fiche,
  chemins,
  sections,
  indicateursListe,
  fichesLiees,
  actionsLiees,
  annexes,
  notes,
  budgets,
};
