### Add an action meta
POST {{host}}/v2/action_meta/test
Authorization: Bearer {{access_token}}
Content-Type: application/json


{
  "action_id": "1.1.1.1",
  "epci_id": "test",
  "meta": {
    "commentaire": "omg",
    "autre": ""
  }
}

### Get all custom actions
GET {{host}}/v2/action_meta/test/all

### Get an action by its path
GET {{host}}/v2/action_meta/test/1.1.1.2

