
### Add a custom action
POST {{host}}/action_custom/v1/
Content-Type: application/json

{
  "uid": "b836d2b4-49c3-4c07-ae5c-5374fae78e0c",
  "epci_id": "test_epci_NOT",
  "mesure_id": "5d4e1246-47ff-410a-9b5b-baa65d2822e9",
  "name": "omg !!!!",
  "description": "such action!"
}

### Add a custom action
POST {{host}}/action_custom/v1/
Content-Type: application/json

{
  "uid": "b836d2b4-49c3-4c07-ae5c-5374fae78exx",
  "epci_id": "test_epci",
  "mesure_id": "5d4e1246-47ff-410a-9b5b-baa65d2822e9",
  "name": "Alice",
  "description": "In wonderland"
}

### Get all custom actions
GET {{host}}/action_custom/v1/test_epci/all

### Get an action by its path
GET {{host}}/action_custom/v1/test_epci/5d4e1246-47ff-410a-9b5b-baa65d2822e9/b836d2b4-49c3-4c07-ae5c-5374fae78e0c

