### Create a new user
### returns 503 if you are no
POST {{host}}/v2/auth/register
Content-Type: application/json

{
  "email": "dev@derfurth.com",
  "nom": "Florian",
  "prenom": "d'Erfurth",
  "vie_privee": "yolo"
}


### Check identity
GET {{host}}/v2/auth/identity
Authorization: Bearer {{access_token}}
