### Write epci
POST {{host}}/v2/epci
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "uid": "abc-def",
  "insee": "",
  "siren": "",
  "nom": "yolo"
}


### Get all epcis
GET {{host}}/v2/epci/all
Authorization: Bearer {{access_token}}

### Get epci
GET {{host}}/v2/epci/test
Authorization: Bearer {{access_token}}
