
### Add a fiche action
POST {{host}}/v2/fiche_action/test
Content-Type: application/json


{
  "avancement": "pas_faite",
  "budget": "1234",
  "commentaire": "",
  "custom_id": "a.b.b",
  "date_debut": "2021-04-04",
  "date_fin": "",
  "description": "yolo",
  "epci_id": "test",
  "porteur": "",
  "referentiel_action_ids": ["citergie/1.1.1"],
  "referentiel_indicateur_ids": ["1a"],
  "titre": "hello",
  "uid": "59fcc45b-ff19-4723-9c18-9a972f4440f3"
}

### Get all fiches
GET {{host}}/v2/fiche_action/test/all


### Get a fiche by its path
GET {{host}}/v2/fiche_action/test/4a1bc73d-aa72-4d28-8424-889643fa29c2

