
### Add an indicateur value
POST {{host}}/indicateur_value/v1/
Content-Type: application/json

{
  "epci_id": "test",
  "indicateur_id": "29",
  "year": 2016,
  "value": "1500"
}

### Add an indicateur value
POST {{host}}/indicateur_value/v1/
Content-Type: application/json

{
  "epci_id": "test",
  "indicateur_id": "29",
  "year": 2018,
  "value": "1900"
}

### Add an indicateur value
POST {{host}}/indicateur_value/v1/
Content-Type: application/json

{
  "epci_id": "test",
  "indicateur_id": "21a",
  "year": 2022,
  "value": "88"
}

### Get all indicateurs values
GET {{host}}/indicateur_value/v1/test/all

### Get an indicateur values by its id
GET {{host}}/indicateur_value/v1/test/29

### Get an indicateur value by fullpath
GET {{host}}/indicateur_value/v1/test/21a/2022

