
### Add an indicateur value
POST {{host}}/v1/indicateur_value/test
Content-Type: application/json

{
  "epci_id": "test",
  "indicateur_id": "29",
  "year": 2016,
  "value": "1502"
}

### Add an indicateur value
POST {{host}}/v1/indicateur_value/test
Content-Type: application/json

{
  "epci_id": "test",
  "indicateur_id": "29",
  "year": 2018,
  "value": "1900"
}

### Add an indicateur value
POST {{host}}/v1/indicateur_value/bad_epci
Content-Type: application/json

{
  "epci_id": "test",
  "indicateur_id": "21a",
  "year": 2022,
  "value": "88"
}

### Get all indicateurs values
GET {{host}}/v1/indicateur_value/test/all

### Get an indicateur values by its id
GET {{host}}/v1/indicateur_value/test/29

### Get an indicateur value by fullpath
GET {{host}}/v1/indicateur_value/test/21a/2022

