import {
  PermissionOperation,
  PermissionOperationEnum,
} from './permission-operation.enum';
import { CollectiviteAccessLevelEnum } from './roles/collectivite-access-level.enum';
import { AuditRole, Role, UserRole } from './roles/role.enum';

export const permissionsByRole: Record<Role, PermissionOperation[]> = {
  [UserRole.CONNECTE]: [],
  [UserRole.VERIFIE]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
  ],
  [UserRole.SUPPORT]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['COLLECTIVITES.READ'],
    PermissionOperationEnum['COLLECTIVITES.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.READ'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ'],
    PermissionOperationEnum['PLANS.FICHES.IMPORT'],
    PermissionOperationEnum['INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.READ'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.READ'],
  ],
  [UserRole.ADEME]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.READ'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
  ],
  [CollectiviteAccessLevelEnum.LECTURE]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['COLLECTIVITES.READ'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.READ'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ'],
    PermissionOperationEnum['INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.READ'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.READ'],
  ],
  [CollectiviteAccessLevelEnum.EDITION_FICHES_INDICATEURS]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['COLLECTIVITES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.DOCUMENTS.CREATE'],
    PermissionOperationEnum['PLANS.FICHES.READ_PILOTED_BY_ME'],
    PermissionOperationEnum['PLANS.FICHES.UPDATE_PILOTED_BY_ME'],
    PermissionOperationEnum['INDICATEURS.READ_PILOTED_BY_ME'],
    PermissionOperationEnum['INDICATEURS.UPDATE_PILOTED_BY_ME'],
    PermissionOperationEnum['INDICATEURS.VALEURS.MUTATE_PILOTED_BY_ME'],
  ],
  ['edition']: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['COLLECTIVITES.READ'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.DOCUMENTS.CREATE'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ'],
    PermissionOperationEnum['REFERENTIELS.MUTATE'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ'],
    PermissionOperationEnum['PLANS.FICHES.CREATE'],
    PermissionOperationEnum['PLANS.FICHES.UPDATE'],
    PermissionOperationEnum['PLANS.FICHES.BULK_UPDATE'],
    PermissionOperationEnum['PLANS.FICHES.DELETE'],
    PermissionOperationEnum['INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.READ'],
    PermissionOperationEnum['INDICATEURS.CREATE'],
    PermissionOperationEnum['INDICATEURS.UPDATE'],
    PermissionOperationEnum['INDICATEURS.VALEURS.MUTATE'],
    PermissionOperationEnum['INDICATEURS.DELETE'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.READ'],
    PermissionOperationEnum['PLANS.MUTATE'],
  ],
  [CollectiviteAccessLevelEnum.ADMIN]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['COLLECTIVITES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TABLEAU-DE-BORD.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.MUTATE'],
    PermissionOperationEnum['COLLECTIVITES.DOCUMENTS.CREATE'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ'],
    PermissionOperationEnum['REFERENTIELS.MUTATE'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ'],
    PermissionOperationEnum['PLANS.FICHES.CREATE'],
    PermissionOperationEnum['PLANS.FICHES.UPDATE'],
    PermissionOperationEnum['PLANS.FICHES.BULK_UPDATE'],
    PermissionOperationEnum['PLANS.FICHES.DELETE'],
    PermissionOperationEnum['INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.READ'],
    PermissionOperationEnum['INDICATEURS.CREATE'],
    PermissionOperationEnum['INDICATEURS.UPDATE'],
    PermissionOperationEnum['INDICATEURS.VALEURS.MUTATE'],
    PermissionOperationEnum['INDICATEURS.DELETE'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.READ'],
    PermissionOperationEnum['PLANS.MUTATE'],
  ],
  [AuditRole.AUDITEUR]: [
    PermissionOperationEnum['COLLECTIVITES.READ_PUBLIC'],
    PermissionOperationEnum['COLLECTIVITES.READ'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.READ'],
    PermissionOperationEnum['COLLECTIVITES.DOCUMENTS.CREATE'],
    PermissionOperationEnum['REFERENTIELS.READ_PUBLIC'],
    PermissionOperationEnum['REFERENTIELS.READ'],
    PermissionOperationEnum['REFERENTIELS.MUTATE'],
    PermissionOperationEnum['REFERENTIELS.AUDIT'],
    PermissionOperationEnum['PLANS.FICHES.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.FICHES.READ'],
    PermissionOperationEnum['INDICATEURS.READ_PUBLIC'],
    PermissionOperationEnum['INDICATEURS.READ'],
    PermissionOperationEnum['INDICATEURS.CREATE'],
    PermissionOperationEnum['INDICATEURS.UPDATE'],
    PermissionOperationEnum['INDICATEURS.VALEURS.MUTATE'],
    PermissionOperationEnum['INDICATEURS.DELETE'],
    PermissionOperationEnum['PLANS.READ_PUBLIC'],
    PermissionOperationEnum['PLANS.READ'],
  ],
};
