import {
  PermissionOperation,
  PermissionOperationEnum,
} from './permission-operation.enum';
import { CollectiviteAccessLevelEnum } from './roles/collectivite-access-level.enum';
import { AuditRole, Role, UserRole } from './roles/role.enum';

export const permissionsByRole: Record<Role, PermissionOperation[]> = {
  [UserRole.CONNECTE]: [],
  [UserRole.VERIFIE]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['PLANS.VISITE'],
  ],
  [UserRole.SUPPORT]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['COLLECTIVITES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.EDITION'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.EDITION'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.LECTURE'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['REFERENTIELS.LECTURE'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.LECTURE'],
    PermissionOperationEnum['PLANS.FICHES.IMPORT'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.LECTURE'],
    PermissionOperationEnum['PLANS.VISITE'],
    PermissionOperationEnum['PLANS.LECTURE'],
  ],
  [UserRole.ADEME]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.LECTURE'],
    PermissionOperationEnum['PLANS.VISITE'],
  ],
  [CollectiviteAccessLevelEnum.LECTURE]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['COLLECTIVITES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.LECTURE'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['REFERENTIELS.LECTURE'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.LECTURE'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.LECTURE'],
    PermissionOperationEnum['PLANS.VISITE'],
    PermissionOperationEnum['PLANS.LECTURE'],
  ],
  [CollectiviteAccessLevelEnum.EDITION_FICHES_INDICATEURS]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['COLLECTIVITES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.EDITION'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.LECTURE'],
    PermissionOperationEnum['PLANS.FICHES.EDITION'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.LECTURE'],
    PermissionOperationEnum['INDICATEURS.EDITION'],
  ],
  [CollectiviteAccessLevelEnum.EDITION]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['COLLECTIVITES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.EDITION'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.EDITION'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['REFERENTIELS.LECTURE'],
    PermissionOperationEnum['REFERENTIELS.EDITION'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.LECTURE'],
    PermissionOperationEnum['PLANS.FICHES.EDITION'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.LECTURE'],
    PermissionOperationEnum['INDICATEURS.EDITION'],
    PermissionOperationEnum['PLANS.VISITE'],
    PermissionOperationEnum['PLANS.LECTURE'],
    PermissionOperationEnum['PLANS.EDITION'],
  ],
  [CollectiviteAccessLevelEnum.ADMIN]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['COLLECTIVITES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TABLEAU-DE-BORD.EDITION'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.EDITION'],
    PermissionOperationEnum['COLLECTIVITES.MEMBRES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.EDITION'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['REFERENTIELS.LECTURE'],
    PermissionOperationEnum['REFERENTIELS.EDITION'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.LECTURE'],
    PermissionOperationEnum['PLANS.FICHES.EDITION'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.LECTURE'],
    PermissionOperationEnum['INDICATEURS.EDITION'],
    PermissionOperationEnum['PLANS.VISITE'],
    PermissionOperationEnum['PLANS.LECTURE'],
    PermissionOperationEnum['PLANS.EDITION'],
  ],
  [AuditRole.AUDITEUR]: [
    PermissionOperationEnum['COLLECTIVITES.VISITE'],
    PermissionOperationEnum['COLLECTIVITES.LECTURE'],
    PermissionOperationEnum['COLLECTIVITES.TAGS.LECTURE'],
    PermissionOperationEnum['REFERENTIELS.VISITE'],
    PermissionOperationEnum['REFERENTIELS.LECTURE'],
    PermissionOperationEnum['REFERENTIELS.EDITION'],
    PermissionOperationEnum['REFERENTIELS.AUDIT'],
    PermissionOperationEnum['PLANS.FICHES.VISITE'],
    PermissionOperationEnum['PLANS.FICHES.LECTURE'],
    PermissionOperationEnum['INDICATEURS.VISITE'],
    PermissionOperationEnum['INDICATEURS.LECTURE'],
    PermissionOperationEnum['INDICATEURS.EDITION'],
    PermissionOperationEnum['PLANS.VISITE'],
    PermissionOperationEnum['PLANS.LECTURE'],
  ],
};
