insert into public.personnalisation (action_id, titre, description)
values  ('cae_4.1.1', 'Réduction potentiel cae 4.1.1 liee AMO', ''),
        ('cae_4.1.2', 'Réduction potentiel cae 4.1.2 liee mobilité interne', ''),
        ('cae_4.1.2.1', 'Désactivation cae 4.1.2.1 liee mobilité interne', ''),
        ('cae_4.1.2.3', 'Désactivation cae 4.1.2.3 liee mobilité interne', ''),
        ('cae_4.1.2.4', 'Désactivation cae 4.1.2.4 liee mobilité interne', ''),
        ('cae_4.2.1', 'Réduction potentiel cae 4.2.1 liee stationnement', ''),
        ('cae_4.2.2', 'Réduction potentiel cae 4.2.2 liee stationnement', ''),
        ('cae_4.2.3', 'Réduction potentiel cae 4.2.3 liee AMO et voirie et population', ''),
        ('cae_4.3.1', 'Réduction potentiel cae 4.3.1 liee voirie', ''),
        ('cae_4.3.2', 'Réduction potentiel cae 4.3.2 liee competence cyclable', ''),
        ('cae_4.3.3', 'Réduction potentiel cae 4.3.3 liee transports en commun', ''),
        ('cae_4.3.4', 'Réduction potentiel cae 4.3.4 liee AOM', ''),
        ('cae_1.2.2', 'Réduction potentiel cae 1.2.2 liee AOM', ''),
        ('cae_1.2.3', 'Réduction potentiel cae 1.2.3 liee competences dechets', ''),
        ('cae_1.2.4', 'Réduction potentiel cae 1.2.4 liee habitat', ''),
        ('cae_1.3.1', 'Réduction potentiel cae 1.3.1 liee competence urba', ''),
        ('cae_1.3.2', 'Réduction potentiel cae 1.3.2 liee possession terrains', ''),
        ('cae_1.3.3', 'Personnalisation cae 1.3.3 liee competence urba', ''),
        ('eci_1.2.2', 'Désactivation eci_1.2.2 liee syndicat', ''),
        ('eci_1.2.3', 'Désactivation eci_1.2.3 liee syndicat', ''),
        ('eci_1.2.4', 'Désactivation eci_1.2.4 liee syndicat', ''),
        ('eci_2.1', 'Désactivation eci_2.1 liee collecte dechets', ''),
        ('eci_2.2', 'Désactivation eci_2.2 liee collecte dechets', ''),
        ('eci_2.3', 'Désactivation eci_2.3 liee traitement dechets', ''),
        ('eci_2.4.0', 'Désactivation eci_2.4.0 liee collecte dechets', ''),
        ('eci_2.4.1', 'Désactivation eci_2.4.1 liee collecte dechets', ''),
        ('eci_2.4.2', 'Désactivation eci_2.4.2 liee collecte dechets', ''),
        ('eci_2.4.3', 'Désactivation eci_2.4.3 liee collecte dechets', ''),
        ('eci_2.4.4', 'Désactivation eci_2.4.4 liee traitement dechets', ''),
        ('eci_2.4.5', 'Désactivation eci_2.4.5 liee traitement dechets', ''),
        ('eci_3.2.0', 'Désactivation eci_3.2.0 liee SPASER', ''),
        ('eci_3.4', 'Désactivation eci_3.4 liee competence dev eco', ''),
        ('eci_3.4.2', 'Désactivation eci_3.4.2 liee etablissement de formation', ''),
        ('eci_3.7.1', 'Modification points eci_3.7.1 liee taille population', ''),
        ('eci_3.7.2', 'Modification points eci_3.7.2 liee taille population', ''),
        ('eci_4.1', 'Désactivation eci_4.1 liee collecte et traitement dechets', ''),
        ('eci_4.2.1', 'Désactivation eci_4.2.1 liee collecte dechets', ''),
        ('eci_4.2.2', 'Désactivation eci_4.2.2 liee collecte dechets', ''),
        ('eci_4.2.3', 'Désactivation eci_4.2.3 liee collecte dechets', ''),
        ('eci_4.2.4', 'Désactivation eci_4.2.4 liee collecte dechets', ''),
        ('eci_4.2.5', 'Désactivation eci_4.2.5 liee syndicat de traitement', ''),
        ('eci_4.3', 'Désactivation eci_4.3 liee competence dev eco', ''),
        ('cae_2.2.3.1', 'Désactivation cae 2.2.3.1 liee DOM-ROM', ''),
        ('cae_2.2.3.2', 'Désactivation cae 2.2.3.2 liee DOM-ROM', ''),
        ('cae_2.2.3.3', 'Désactivation cae 2.2.3.3 liee DOM-ROM', ''),
        ('cae_2.2.3', 'Réduction potentiel cae 2.2.3 liee eau chaude sanitaire', ''),
        ('cae_2.3.1', 'Réduction potentiel cae 2.3.1 liee eclairage public', ''),
        ('cae_2.3.3', 'Réduction potentiel cae 2.3.3 liee voirie', ''),
        ('cae_6.1.2', 'Réduction potentiel cae 6.1.2 liee commune', ''),
        ('cae_6.2.1', 'Reduction potentiel cae 6.2.1 liee logement-habitat', ''),
        ('cae_6.2.2', 'Reduction potentiel cae 6.2.2 liee logement-habitat', ''),
        ('cae_6.2.3', 'Reduction potentiel cae 6.2.3 liee logement-habitat', ''),
        ('cae_6.2.4', 'Reduction potentiel cae 6.2.4 liee developpement economique', ''),
        ('cae_6.3.1', 'Reduction potentiel cae 6.3.1 liee developpement economique', ''),
        ('cae_6.3.1.4', 'Désactivation cae 6.3.1.4 liee tissu economique', ''),
        ('cae_6.3.1.3', 'Modification potentiel cae 6.3.1.3 liee tissu economique', ''),
        ('cae_6.3.1.5', 'Modification potentiel cae 6.3.1.5 liee tissu economique', ''),
        ('cae_6.3.2', 'Reduction potentiel cae 6.3.2 liee tourisme', ''),
        ('cae_6.4.1', 'Reduction potentiel cae 6.4.1 liee surfaces agricoles', ''),
        ('cae_6.4.1.6', 'Modification points cae 6.4.1.6 liee DOM', ''),
        ('cae_6.4.1.8', 'Modification points cae 6.4.1.8 liee DOM', ''),
        ('cae_6.4.2', 'Reduction potentiel cae 6.4.2 liee surfaces forestieres', ''),
        ('cae_6.5.2.5', 'Désactivation cae 6.5.2.5 liee a publicite', ''),
        ('cae_6.5.2', 'Reduction potentiel cae 6.5.2 liee a publicite', ''),
        ('cae_6.5.3', 'Reduction potentiel cae 6.5.3 liee scolaire', ''),
        ('cae_3.1.1', 'Réduction potentiel cae 3.1.1 liee autorités organisatrices énergie', ''),
        ('cae_3.1.2', 'Réduction potentiel cae 3.1.2 liee autorités organisatrices énergie', ''),
        ('cae_3.1.2.2', 'Réduction potentiel cae 3.1.2.2 liee fournisseurs énergie', ''),
        ('cae_3.2.1', 'Modification points cae 3.2.1 liee DOM', ''),
        ('cae_3.2.1.1', 'Réduction potentiel cae 3.2.1.1', ''),
        ('cae_3.2.1.2', 'Réduction potentiel cae 3.2.1.2', ''),
        ('cae_3.2.1.3', 'Réduction potentiel cae 3.2.1.3', ''),
        ('cae_3.2.2', 'Modification points cae 3.2.2 liee DOM', ''),
        ('cae_3.2.3', 'Modification points cae 3.2.3 liee DOM', ''),
        ('cae_3.3.1', 'Réduction potentiel cae 3.3.1 liee eau potable', ''),
        ('cae_3.3.2', 'Réduction potentiel cae 3.3.2 liee assainissement collectif', ''),
        ('cae_3.3.3', 'Réduction potentiel cae 3.3.3 liee assainissement', ''),
        ('cae_3.3.5', 'Réduction potentiel cae 3.3.5 liee dechets', '');