-- source https://www.iso.org/obp/ui/fr/#iso:code:3166:FR
insert into stats.iso_3166 (type, code, nom, variante, langue)
values ('département métropolitain', 'FR-01', 'Ain', 'fr', 'FR-ARA'),
       ('département métropolitain', 'FR-02', 'Aisne', 'fr', 'FR-HDF'),
       ('département métropolitain', 'FR-03', 'Allier', 'fr', 'FR-ARA'),
       ('département métropolitain', 'FR-06', 'Alpes-Maritimes', 'fr', 'FR-PAC'),
       ('département métropolitain', 'FR-04', 'Alpes-de-Haute-Provence', 'fr', 'FR-PAC'),
       ('collectivité européenne', 'FR-6AE', 'Alsace', 'fr', 'FR-GES'),
       ('département métropolitain', 'FR-08', 'Ardennes', 'fr', 'FR-GES'),
       ('département métropolitain', 'FR-07', 'Ardèche', 'fr', 'FR-ARA'),
       ('département métropolitain', 'FR-09', 'Ariège', 'fr', 'FR-OCC'),
       ('département métropolitain', 'FR-10', 'Aube', 'fr', 'FR-GES'),
       ('département métropolitain', 'FR-11', 'Aude', 'fr', 'FR-OCC'),
       ('région métropolitaine', 'FR-ARA', 'Auvergne-Rhône-Alpes', 'fr', null),
       ('département métropolitain', 'FR-12', 'Aveyron', 'fr', 'FR-OCC'),
       ('département métropolitain', 'FR-67', 'Bas-Rhin', 'fr', 'FR-6AE'),
       ('département métropolitain', 'FR-13', 'Bouches-du-Rhône', 'fr', 'FR-PAC'),
       ('région métropolitaine', 'FR-BFC', 'Bourgogne-Franche-Comté', 'fr', null),
       ('région métropolitaine', 'FR-BRE', 'Bretagne', 'fr', null),
       ('département métropolitain', 'FR-14', 'Calvados', 'fr', 'FR-NOR'),
       ('département métropolitain', 'FR-15', 'Cantal', 'fr', 'FR-ARA'),
       ('région métropolitaine', 'FR-CVL', 'Centre-Val de Loire', 'fr', null),
       ('département métropolitain', 'FR-16', 'Charente', 'fr', 'FR-NAQ'),
       ('département métropolitain', 'FR-17', 'Charente-Maritime', 'fr', 'FR-NAQ'),
       ('département métropolitain', 'FR-18', 'Cher', 'fr', 'FR-CVL'),
       ('dépendance', 'FR-CP', 'Clipperton', 'fr', null),
       ('département métropolitain', 'FR-19', 'Corrèze', 'fr', 'FR-NAQ'),
       ('collectivité métropolitaine à statut particulier', 'FR-20R', 'Corse', 'fr', null),
       ('département métropolitain', 'FR-2A', 'Corse-du-Sud', 'fr', 'FR-20R'),
       ('département métropolitain', 'FR-23', 'Creuse', 'fr', 'FR-NAQ'),
       ('département métropolitain', 'FR-21', 'Côte-d''Or', 'fr', 'FR-BFC'),
       ('département métropolitain', 'FR-22', 'Côtes-d''Armor', 'fr', 'FR-BRE'),
       ('département métropolitain', 'FR-79', 'Deux-Sèvres', 'fr', 'FR-NAQ'),
       ('département métropolitain', 'FR-24', 'Dordogne', 'fr', 'FR-NAQ'),
       ('département métropolitain', 'FR-25', 'Doubs', 'fr', 'FR-BFC'),
       ('département métropolitain', 'FR-26', 'Drôme', 'fr', 'FR-ARA'),
       ('département métropolitain', 'FR-91', 'Essonne', 'fr', 'FR-IDF'),
       ('département métropolitain', 'FR-27', 'Eure', 'fr', 'FR-NOR'),
       ('département métropolitain', 'FR-28', 'Eure-et-Loir', 'fr', 'FR-CVL'),
       ('département métropolitain', 'FR-29', 'Finistère', 'fr', 'FR-BRE'),
       ('département métropolitain', 'FR-30', 'Gard', 'fr', 'FR-OCC'),
       ('département métropolitain', 'FR-32', 'Gers', 'fr', 'FR-OCC'),
       ('département métropolitain', 'FR-33', 'Gironde', 'fr', 'FR-NAQ'),
       ('région métropolitaine', 'FR-GES', 'Grand Est', 'fr', null),
       ('collectivité départementale d''outre-mer', 'FR-971', 'Guadeloupe', 'fr', null),
       ('collectivité territoriale unique d''outre-mer', 'FR-973', 'Guyane', 'fr', null),
       ('département métropolitain', 'FR-68', 'Haut-Rhin', 'fr', 'FR-6AE'),
       ('département métropolitain', 'FR-2B', 'Haute-Corse', 'fr', 'FR-20R'),
       ('département métropolitain', 'FR-31', 'Haute-Garonne', 'fr', 'FR-OCC'),
       ('département métropolitain', 'FR-43', 'Haute-Loire', 'fr', 'FR-ARA'),
       ('département métropolitain', 'FR-52', 'Haute-Marne', 'fr', 'FR-GES'),
       ('département métropolitain', 'FR-74', 'Haute-Savoie', 'fr', 'FR-ARA'),
       ('département métropolitain', 'FR-70', 'Haute-Saône', 'fr', 'FR-BFC'),
       ('département métropolitain', 'FR-87', 'Haute-Vienne', 'fr', 'FR-NAQ'),
       ('département métropolitain', 'FR-05', 'Hautes-Alpes', 'fr', 'FR-PAC'),
       ('département métropolitain', 'FR-65', 'Hautes-Pyrénées', 'fr', 'FR-OCC'),
       ('région métropolitaine', 'FR-HDF', 'Hauts-de-France', 'fr', null),
       ('département métropolitain', 'FR-92', 'Hauts-de-Seine', 'fr', 'FR-IDF'),
       ('département métropolitain', 'FR-34', 'Hérault', 'fr', 'FR-OCC'),
       ('département métropolitain', 'FR-35', 'Ille-et-Vilaine', 'fr', 'FR-BRE'),
       ('département métropolitain', 'FR-36', 'Indre', 'fr', 'FR-CVL'),
       ('département métropolitain', 'FR-37', 'Indre-et-Loire', 'fr', 'FR-CVL'),
       ('département métropolitain', 'FR-38', 'Isère', 'fr', 'FR-ARA'),
       ('département métropolitain', 'FR-39', 'Jura', 'fr', 'FR-BFC'),
       ('collectivité départementale d''outre-mer', 'FR-974', 'La Réunion', 'fr', null),
       ('département métropolitain', 'FR-40', 'Landes', 'fr', 'FR-NAQ'),
       ('département métropolitain', 'FR-41', 'Loir-et-Cher', 'fr', 'FR-CVL'),
       ('département métropolitain', 'FR-42', 'Loire', 'fr', 'FR-ARA'),
       ('département métropolitain', 'FR-44', 'Loire-Atlantique', 'fr', 'FR-PDL'),
       ('département métropolitain', 'FR-45', 'Loiret', 'fr', 'FR-CVL'),
       ('département métropolitain', 'FR-46', 'Lot', 'fr', 'FR-OCC'),
       ('département métropolitain', 'FR-47', 'Lot-et-Garonne', 'fr', 'FR-NAQ'),
       ('département métropolitain', 'FR-48', 'Lozère', 'fr', 'FR-OCC'),
       ('département métropolitain', 'FR-49', 'Maine-et-Loire', 'fr', 'FR-PDL'),
       ('département métropolitain', 'FR-50', 'Manche', 'fr', 'FR-NOR'),
       ('département métropolitain', 'FR-51', 'Marne', 'fr', 'FR-GES'),
       ('collectivité territoriale unique d''outre-mer', 'FR-972',
        'Martinique', 'fr', null),
       ('département métropolitain', 'FR-53', 'Mayenne', 'fr', 'FR-PDL'),
       ('collectivité départementale d''outre-mer', 'FR-976', 'Mayotte', 'fr', null),
       ('département métropolitain', 'FR-54', 'Meurthe-et-Moselle', 'fr', 'FR-GES'),
       ('département métropolitain', 'FR-55', 'Meuse', 'fr', 'FR-GES'),
       ('département métropolitain', 'FR-56', 'Morbihan', 'fr', 'FR-BRE'),
       ('département métropolitain', 'FR-57', 'Moselle', 'fr', 'FR-GES'),
       ('collectivité métropolitaine à statut particulier', 'FR-69M', 'Métropole de Lyon', 'fr', 'FR-ARA'),
       ('département métropolitain', 'FR-58', 'Nièvre', 'fr', 'FR-BFC'),
       ('département métropolitain', 'FR-59', 'Nord', 'fr', 'FR-HDF'),
       ('région métropolitaine', 'FR-NOR', 'Normandie', 'fr', null),
       ('région métropolitaine', 'FR-NAQ', 'Nouvelle-Aquitaine', 'fr', null),
       ('collectivité d’outre-mer à statut particulier', 'FR-NC',
        'Nouvelle-Calédonie', 'fr', null),
       ('région métropolitaine', 'FR-OCC', 'Occitanie', 'fr', null),
       ('département métropolitain', 'FR-60', 'Oise', 'fr', 'FR-HDF'),
       ('département métropolitain', 'FR-61', 'Orne', 'fr', 'FR-NOR'),
       ('collectivité métropolitaine à statut particulier', 'FR-75C', 'Paris', 'fr', 'FR-IDF'),
       ('département métropolitain', 'FR-62', 'Pas-de-Calais', 'fr', 'FR-HDF'),
       ('région métropolitaine', 'FR-PDL', 'Pays de la Loire', 'fr', null),
       ('collectivité d''outre-mer', 'FR-PF', 'Polynésie française',
        'fr', null),
       ('région métropolitaine', 'FR-PAC', 'Provence-Alpes-Côte d''Azur', 'fr', null),
       ('département métropolitain', 'FR-63', 'Puy-de-Dôme', 'fr', 'FR-ARA'),
       ('département métropolitain', 'FR-64', 'Pyrénées-Atlantiques', 'fr', 'FR-NAQ'),
       ('département métropolitain', 'FR-66', 'Pyrénées-Orientales', 'fr', 'FR-OCC'),
       ('département métropolitain', 'FR-69', 'Rhône', 'fr', 'FR-ARA'),
       ('collectivité d''outre-mer', 'FR-BL', 'Saint-Barthélemy', 'fr',
        null),
       ('collectivité d''outre-mer', 'FR-MF', 'Saint-Martin', 'fr',
        null),
       ('collectivité d''outre-mer', 'FR-PM',
        'Saint-Pierre-et-Miquelon', 'fr', null),
       ('département métropolitain', 'FR-72', 'Sarthe', 'fr', 'FR-PDL'),
       ('département métropolitain', 'FR-73', 'Savoie', 'fr', 'FR-ARA'),
       ('département métropolitain', 'FR-71', 'Saône-et-Loire', 'fr', 'FR-BFC'),
       ('département métropolitain', 'FR-76', 'Seine-Maritime', 'fr', 'FR-NOR'),
       ('département métropolitain', 'FR-93', 'Seine-Saint-Denis', 'fr', 'FR-IDF'),
       ('département métropolitain', 'FR-77', 'Seine-et-Marne', 'fr', 'FR-IDF'),
       ('département métropolitain', 'FR-80', 'Somme', 'fr', 'FR-HDF'),
       ('département métropolitain', 'FR-81', 'Tarn', 'fr', 'FR-OCC'),
       ('département métropolitain', 'FR-82', 'Tarn-et-Garonne', 'fr', 'FR-OCC'),
       ('territoire d''outre-mer', 'FR-TF',
        'Terres australes françaises', 'fr', null),
       ('département métropolitain', 'FR-90', 'Territoire de Belfort', 'fr', 'FR-BFC'),
       ('département métropolitain', 'FR-95', 'Val-d''Oise', 'fr', 'FR-IDF'),
       ('département métropolitain', 'FR-94', 'Val-de-Marne', 'fr', 'FR-IDF'),
       ('département métropolitain', 'FR-83', 'Var', 'fr', 'FR-PAC'),
       ('département métropolitain', 'FR-84', 'Vaucluse', 'fr', 'FR-PAC'),
       ('département métropolitain', 'FR-85', 'Vendée', 'fr', 'FR-PDL'),
       ('département métropolitain', 'FR-86', 'Vienne', 'fr', 'FR-NAQ'),
       ('département métropolitain', 'FR-88', 'Vosges', 'fr', 'FR-GES'),
       ('collectivité d''outre-mer', 'FR-WF', 'Wallis-et-Futuna', 'fr', null),
       ('département métropolitain', 'FR-89', 'Yonne', 'fr', 'FR-BFC'),
       ('département métropolitain', 'FR-78', 'Yvelines', 'fr', 'FR-IDF'),
       ('région métropolitaine', 'FR-IDF', 'Île-de-France', 'fr', null);
