name: Déploiement de l'auth
run-name: Déploiement du module d'auth. sur ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Où déployer
        options:
          - preprod
          - staging
          - prod

jobs:
  build-auth:
    name: Build le module d'auth
    uses: ./.github/workflows/build-auth.yml
    with:
      environment: ${{ github.event.inputs.target }}
      push: ${{ !env.ACT }}
    secrets: inherit

  deploy-auth:
    name: Déploie le module d'auth
    needs: build-auth
    environment: ${{ github.event.inputs.target }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Deploy auth on Koyeb
        uses: ./.github/actions/koyeb-deploy
        with:
          api_token: ${{ secrets.KOYEB_API_KEY }}
          environment: ${{ github.event.inputs.target }}
          component: auth
          image_path: ${{ needs.build-auth.outputs.image_path }}
