name: Déploiement de l'app

permissions:
  contents: read

run-name: Déploiement de l'app ${{ github.event.inputs.is-test-app == 'true' && '(test)' || '' }} sur ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Quel environnement ?
        options:
          - preprod
          - staging
          - prod
      is-test-app:
        type: boolean
        description: Application de test

jobs:
  build-app:
    name: Build l'app
    if: ${{ github.event.inputs.is-test-app != 'true' }}
    environment: ${{ github.event.inputs.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.image.outputs.path }}

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: meta
        uses: ./.github/actions/build-metadata

      - uses: ./.github/actions/docker-login
        if: ${{ !env.ACT }}
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: image
        uses: ./.github/actions/docker-image-path
        with:
          username: incubateur-ademe
          image: tet-app
          tag: ${{ github.event.inputs.target }}-${{ steps.meta.outputs.git-short-hash }}

      - name: Build et push de l'image app
        uses: ./.github/actions/docker-build-push
        env:
          BRYNTUM_ACCESS_TOKEN: ${{ secrets.BRYNTUM_ACCESS_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        with:
          dockerfile: apps/app/Dockerfile
          image: ${{ steps.image.outputs.path }}
          cache-scope: tet-app
          push: ${{ !env.ACT }}
          secrets: |
            bryntum_token=BRYNTUM_ACCESS_TOKEN
            sentry_auth_token=SENTRY_AUTH_TOKEN
          build-args: |
            ANON_KEY=${{ secrets.ANON_KEY }}
            API_URL=${{ secrets.API_URL }}
            APP_URL=${{ vars.APP_URL }}
            BACKEND_URL=${{ vars.BACKEND_URL }}
            PANIER_URL=${{ vars.PANIER_URL }}
            CRISP_WEBSITE_ID=${{ vars.CRISP_WEBSITE_ID }}
            SENTRY_DSN=${{ vars.SENTRY_DSN }}
            GIT_SHORT_HASH=${{ steps.meta.outputs.git-short-hash }}
            GIT_COMMIT_TIMESTAMP=${{ steps.meta.outputs.git-commit-timestamp }}
            APPLICATION_VERSION=${{ steps.meta.outputs.application-version }}
            ENV_NAME=${{ github.event.inputs.target }}

  build-test-app:
    name: Build l'app de test # TODO: only on variable change, improve to avoid duplicate
    if: ${{ github.event.inputs.is-test-app == 'true' }}
    environment: ${{ github.event.inputs.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.image.outputs.path }}

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: meta
        uses: ./.github/actions/build-metadata

      - uses: ./.github/actions/docker-login
        if: ${{ !env.ACT }}
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: image
        uses: ./.github/actions/docker-image-path
        with:
          username: incubateur-ademe
          image: tet-app-test
          tag: ${{ github.event.inputs.target }}-${{ steps.meta.outputs.git-short-hash }}

      - name: Build et push de l'image app de test
        uses: ./.github/actions/docker-build-push
        env:
          BRYNTUM_ACCESS_TOKEN: ${{ secrets.BRYNTUM_ACCESS_TOKEN }}
        with:
          dockerfile: apps/app/Dockerfile
          image: ${{ steps.image.outputs.path }}
          cache-scope: tet-app-test
          push: ${{ !env.ACT }}
          secrets: |
            bryntum_token=BRYNTUM_ACCESS_TOKEN
          build-args: |
            ANON_KEY=${{ secrets.ANON_KEY }}
            API_URL=${{ secrets.API_URL }}
            APP_URL=${{ vars.APP_URL }}
            BACKEND_URL=${{ vars.BACKEND_TEST_URL }}
            PANIER_URL=${{ vars.PANIER_URL }}
            CRISP_WEBSITE_ID=${{ vars.CRISP_WEBSITE_ID }}
            SENTRY_DSN=${{ vars.SENTRY_DSN }}
            GIT_SHORT_HASH=${{ steps.meta.outputs.git-short-hash }}
            GIT_COMMIT_TIMESTAMP=${{ steps.meta.outputs.git-commit-timestamp }}
            APPLICATION_VERSION=${{ steps.meta.outputs.application-version }}
            ENV_NAME=${{ github.event.inputs.target }}

  deploy-app:
    name: Déploie l'app
    if: ${{ github.event.inputs.is-test-app != 'true' }}
    needs: build-app
    environment: ${{ github.event.inputs.target }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - id: meta
        uses: ./.github/actions/build-metadata

      - uses: ./.github/actions/koyeb-cli
        with:
          api-key: ${{ secrets.KOYEB_API_KEY }}

      - name: Déploie l'app sur Koyeb
        env:
          ENV_NAME: ${{ github.event.inputs.target }}
          IMAGE: ${{ needs.build-app.outputs.image }}
          DEPLOYMENT_TIMESTAMP: ${{ steps.meta.outputs.deployment-timestamp }}
        run: >
          koyeb services update $ENV_NAME-app/front
          --docker "$IMAGE"
          --docker-private-registry-secret ghcr
          --env POSTHOG_HOST=@POSTHOG_HOST
          --env POSTHOG_KEY=@POSTHOG_KEY
          --env DEPLOYMENT_TIMESTAMP=$DEPLOYMENT_TIMESTAMP

  deploy-test-app:
    name: Déploie l'app de test
    if: ${{ github.event.inputs.is-test-app == 'true' }}
    needs: build-test-app
    environment: preprod-koyeb
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - id: test-app-name
        uses: ./.github/actions/test-app-name
        with:
          branch-name: ${{ github.ref_name }}

      - uses: ./.github/actions/koyeb-cli
        with:
          api-key: ${{ secrets.KOYEB_API_KEY }}

      - name: Déploie (ou crée) l'app de test sur Koyeb
        env:
          IMAGE: ${{ needs.build-test-app.outputs.image }}
          NAME: ${{ steps.test-app-name.outputs.name }}
        run: |
          if koyeb apps get "test-app-$NAME" >/dev/null 2>&1; then
            echo "App de test déjà déployée sur Koyeb à test-app-$NAME, mise à jour..."
            koyeb services update "test-app-$NAME/test-app-$NAME" \
              --docker "$IMAGE" --docker-private-registry-secret ghcr
          else
            echo "App de test introuvable sur Koyeb à test-app-$NAME, création avec $IMAGE..."
            koyeb apps init "test-app-$NAME" \
              --docker "$IMAGE" --docker-private-registry-secret ghcr \
              --type web --port 3000:http --route /:3000 --env PORT=3000 \
              --regions par
          fi
