name: Déploiement à la demande du backend

permissions:
  contents: read

run-name: Déploiement du backend sur ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Quel environnement ?
        options:
          - preprod
          - staging
          - prod
      is-test-backend:
        type: boolean
        description: Backend de test

jobs:
  build-backend:
    name: Build le backend
    uses: ./.github/workflows/build-backend.yml
    with:
      environment: ${{ github.event.inputs.target }}
      push: ${{ !env.ACT }}
    secrets: inherit

  deploy-backend:
    name: Déploie le backend
    if: ${{ github.event.inputs.is-test-backend != 'true' }}
    needs: build-backend
    environment: ${{ github.event.inputs.target }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Deploy backend on Koyeb
        uses: ./.github/actions/koyeb-deploy
        with:
          api_token: ${{ secrets.KOYEB_API_KEY }}
          environment: ${{ github.event.inputs.target }}
          component: backend
          image_path: ${{ needs.build-backend.outputs.image_path }}
          trajectoire_snbc_sheet_id: ${{ vars.TRAJECTOIRE_SNBC_SHEET_ID }}
          trajectoire_snbc_xlsx_id: ${{ vars.TRAJECTOIRE_SNBC_XLSX_ID }}
          trajectoire_snbc_result_folder_id: ${{ vars.TRAJECTOIRE_SNBC_RESULT_FOLDER_ID }}
          referentiel_te_sheet_id: ${{ vars.REFERENTIEL_TE_SHEET_ID }}
          referentiel_cae_sheet_id: ${{ vars.REFERENTIEL_CAE_SHEET_ID }}
          referentiel_eci_sheet_id: ${{ vars.REFERENTIEL_ECI_SHEET_ID }}
          indicateur_definitions_sheet_id: ${{ vars.INDICATEUR_DEFINITIONS_SHEET_ID }}

  deploy-test-backend:
    name: Déploie le backend de test
    if: ${{ github.event.inputs.is-test-backend == 'true' }}
    needs: build-backend
    environment: ${{ github.event.inputs.target }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Deploy test backend on Koyeb
        uses: ./.github/actions/koyeb-deploy
        with:
          api_token: ${{ secrets.KOYEB_API_KEY }}
          environment: ${{ github.event.inputs.target }}
          component: backend
          image_path: ${{ needs.build-backend.outputs.image_path }}
          service_name: test-${{ github.event.inputs.target }}-backend
          trajectoire_snbc_sheet_id: ${{ vars.TRAJECTOIRE_SNBC_SHEET_ID }}
          trajectoire_snbc_xlsx_id: ${{ vars.TRAJECTOIRE_SNBC_XLSX_ID }}
          trajectoire_snbc_result_folder_id: ${{ vars.TRAJECTOIRE_SNBC_RESULT_FOLDER_ID }}
          referentiel_te_sheet_id: ${{ vars.REFERENTIEL_TE_SHEET_ID }}
          referentiel_cae_sheet_id: ${{ vars.REFERENTIEL_CAE_SHEET_ID }}
          referentiel_eci_sheet_id: ${{ vars.REFERENTIEL_ECI_SHEET_ID }}
          indicateur_definitions_sheet_id: ${{ vars.INDICATEUR_DEFINITIONS_SHEET_ID }}
