name: Déploiement à la demande du panier
run-name: Déploiement du panier sur ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Où déployer
        options:
          - preprod
          - staging
          - prod

jobs:
  build-panier:
    name: Build le panier
    uses: ./.github/workflows/build-panier.yml
    with:
      environment: ${{ github.event.inputs.target }}
      push: ${{ !env.ACT }}
    secrets: inherit

  deploy-panier:
    name: Déploie le panier
    needs: build-panier
    environment: ${{ github.event.inputs.target }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Deploy panier on Koyeb
        uses: ./.github/actions/koyeb-deploy
        with:
          api_token: ${{ secrets.KOYEB_API_KEY }}
          environment: ${{ github.event.inputs.target }}
          component: panier
          image_path: ${{ needs.build-panier.outputs.image_path }}
