name: Déploiement du site

permissions:
  contents: read
  packages: write

run-name: Déploiement du site sur ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Où déployer
        options:
          - preprod
          - staging
          - prod

jobs:
  deploy-site:
    name: Déploie le site
    environment: ${{ github.event.inputs.target }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: meta
        uses: ./.github/actions/build-metadata

      - uses: ./.github/actions/docker-login
        if: ${{ !env.ACT }}
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: image
        uses: ./.github/actions/docker-image-path
        with:
          username: incubateur-ademe
          image: tet-site
          tag: ${{ github.event.inputs.target }}-${{ steps.meta.outputs.git-short-hash }}

      - name: Build et push de l'image site
        uses: ./.github/actions/docker-build-push
        env:
          BRYNTUM_ACCESS_TOKEN: ${{ secrets.BRYNTUM_ACCESS_TOKEN }}
        with:
          dockerfile: apps/site/Dockerfile
          image: ${{ steps.image.outputs.path }}
          cache-scope: tet-site
          push: ${{ !env.ACT }}
          secrets: |
            bryntum_token=BRYNTUM_ACCESS_TOKEN
          build-args: |
            STRAPI_KEY=${{ secrets.STRAPI_KEY }}
            STRAPI_URL=${{ secrets.STRAPI_URL }}
            ANON_KEY=${{ secrets.ANON_KEY }}
            API_URL=${{ secrets.API_URL }}
            POSTHOG_HOST=${{ secrets.POSTHOG_HOST }}
            POSTHOG_KEY=${{ secrets.POSTHOG_KEY }}
            AXEPTIO_ID=${{ vars.AXEPTIO_ID }}
            APP_URL=${{ vars.APP_URL }}
            PANIER_URL=${{ vars.PANIER_URL }}
            CRISP_WEBSITE_ID=${{ vars.CRISP_WEBSITE_ID }}

      - uses: ./.github/actions/koyeb-cli
        with:
          api-key: ${{ secrets.KOYEB_API_KEY }}

      - name: Déploie le site sur Koyeb
        env:
          ENV_NAME: ${{ github.event.inputs.target }}
          IMAGE: ${{ steps.image.outputs.path }}
        run: >
          koyeb services update $ENV_NAME-site/front
          --docker "$IMAGE"
          --docker-private-registry-secret ghcr
