name: Déploiement du site
run-name: Déploiement du site sur ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Où déployer
        options:
          - preprod
          - staging
          - prod

jobs:
  build-site:
    name: Build le site
    uses: ./.github/workflows/build-site.yml
    with:
      environment: ${{ github.event.inputs.target }}
      push: ${{ !env.ACT }}
    secrets: inherit

  deploy-site:
    name: Déploie le site
    needs: build-site
    environment: ${{ github.event.inputs.target }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Deploy site on Koyeb
        uses: ./.github/actions/koyeb-deploy
        with:
          api_token: ${{ secrets.KOYEB_API_KEY }}
          environment: ${{ github.event.inputs.target }}
          component: site
          image_path: ${{ needs.build-site.outputs.image_path }}
