# Unit test package api
name: test-package-api

permissions:
  contents: read

on:
  workflow_call:

jobs:
  test-package-api:
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-login
        if: ${{ !env.ACT }}
        with:
          password: ${{ secrets.GH_TOKEN }}

      - uses: ./.github/actions/pnpm-install

      - name: Start supabase
        id: start
        uses: ./.github/actions/supabase-start
        with:
          network: ${{ vars.SUPABASE_NETWORK }}
          pull: ${{ !env.ACT }}

      - name: Run tests
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.SUPABASE_API_URL }}
          NEXT_PUBLIC_SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: pnpm test:api
