# Unit test package api
name: test-package-api

on:
  workflow_call:

jobs:
  test-package-api:
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-login
        if: ${{ !env.ACT }}
        with:
          password: ${{ secrets.GH_TOKEN }}

      - uses: ./.github/actions/pnpm-install

      - name: Start supabase
        id: start
        uses: ./.github/actions/supabase-start
        with:
          network: ${{ vars.SUPABASE_NETWORK }}
          pull: ${{ !env.ACT }}

      - run: pnpm test:api
