name: Markdowns to JSONs

on:
  pull_request:
    paths:
      - 'markdown/**/*.md'
  workflow_dispatch:

jobs:
  update-json:
    name: Lecture et conversion des fichiers Markdown en JSON
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: dev

    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions-setup@v1
        with:
          version: ^0.8.0
      - uses: supabase/setup-cli@v1

      - name: Login into registry
        run: earthly --use-inline-cache +docker-dev-login --GH_USER=${{ secrets.GH_USER }} --GH_TOKEN=${{ secrets.GH_TOKEN }}

      - name: Convertit les fichiers Markdown en JSON
        run: earthly +business-parse

      - name: Setup le projet
        run: earthly +setup-env

      - name: Lance le projet
        run: >
          earthly --use-inline-cache +dev
          --stop=no --datalayer=yes --business=yes --app=no --auth=no --version=HEAD
          --DB_URL=${{ secrets.DB_URL }}
          --SERVICE_ROLE_KEY=${{ secrets.SERVICE_ROLE_KEY }}
          --API_URL=${{ secrets.API_URL }}
          --ANON_KEY=${{ secrets.ANON_KEY }}
          --JWT_SECRET=${{ secrets.JWT_SECRET }}
          --REFERENTIEL_TE_SHEET_ID=${{ vars.REFERENTIEL_TE_SHEET_ID }}
          --REFERENTIEL_CAE_SHEET_ID=${{ vars.REFERENTIEL_CAE_SHEET_ID }}
          --REFERENTIEL_ECI_SHEET_ID=${{ vars.REFERENTIEL_ECI_SHEET_ID }}
          --INDICATEUR_DEFINITIONS_SHEET_ID=${{ vars.INDICATEUR_DEFINITIONS_SHEET_ID }}
          --TRAJECTOIRE_SNBC_XLSX_ID=${{ vars.TRAJECTOIRE_SNBC_XLSX_ID }}
          --GCLOUD_SERVICE_ACCOUNT_KEY=${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Lance les tests business
        run: earthly +business-test

      - name: Commit les fichiers JSON
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: Contenus json générés depuis les Markdowns
