export const ANNEE_REFERENCE_SNBC_V2 = 2015;
export const ANNEE_JALON2 = 2050;
export const DATE_FIN_SNBC_V2 = `${ANNEE_JALON2}-01-01`;
export const DATE_DEBUT_SNBC_V2_REFERENCE = `${ANNEE_REFERENCE_SNBC_V2}-01-01`;
export const DATE_FIN_SNBC_V2_REFERENCE = `${ANNEE_REFERENCE_SNBC_V2}-12-31`;

const ALDO_ANNEE_REFERENCE = 2018;
export const SNBC_ALDO_DATE_DEBUT_REFERENCE = `${ALDO_ANNEE_REFERENCE}-01-01`;
export const SNBC_ALDO_DATE_FIN_REFERENCE = `${ALDO_ANNEE_REFERENCE}-12-31`;
