### Authenticate as a user
POST {{api}}/auth/v1/token?grant_type=password
apikey: {{anon}}
Content-Type: application/json

{
  "email": "{{yolo_mail}}",
  "password": "{{yolo_pass}}"
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.log('token is ' + response.body['access_token']);
    client.global.set("auth_token", response.body['access_token']);
%}

### Upsert une discussion
POST {{api}}/rest/v1/action_discussion?on_conflict=id
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
prefer: return=representation, resolution=merge-duplicates
Content-Type: application/json

{
  "collectivite_id": 1,
  "action_id": "eci_1.1.1.1"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
    client.global.set("discussion_id", response.body[0]['id']);
%}


### Ajoute un commentaire à une discussion
POST {{api}}/rest/v1/action_discussion_commentaire
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
prefer: return=representation
Content-Type: application/json

{
  "discussion_id": {{discussion_id}},
  "message": "yo !"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}


### Get les discussions d'une action
GET {{api}}/rest/v1/action_discussion_feed?action_id=eq.eci_1.1.1.1
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json
