### Authenticate as a user
POST {{api}}/auth/v1/token?grant_type=password
apikey: {{anon}}
Content-Type: application/json

{
  "email": "{{youlou_mail}}",
  "password": "{{youlou_pass}}"
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.log('token is ' + response.body['access_token']);
    client.global.set("auth_token", response.body['access_token']);
%}

### List audit display
GET {{api}}/rest/v1/audit
apikey: {{anon}}
Authorization: Bearer {{auth_token}}

### List action_audit_state display
GET {{api}}/rest/v1/action_audit_state?collectivite_id=eq.1&referentiel=eq.eci
apikey: {{anon}}
Authorization: Bearer {{auth_token}}

### Upsert un audit
POST {{api}}/rest/v1/audit
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
prefer: return=representation
Content-Type: application/json

{
  "collectivite_id": 2,
  "referentiel": "eci"
}

> {%
    client.test("Create executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Ajout d'un auditeur
POST {{api}}/rest/v1/audit_auditeur
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
prefer: return=representation
Content-Type: application/json

{
  "audit_id": 1,
  "auditeur": "4ecc7d3a-7484-4a1c-8ac8-930cdacd2561"
}

> {%
    client.test("Create executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}



### Upsert un action_audit_state dans la vue.
POST {{api}}/rest/v1/action_audit_state
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
prefer: return=representation
Content-Type: application/json

{
  "collectivite_id": 1,
  "action_id": "eci_2.5",
  "ordre_du_jour" : true,
  "avis" :  "avis test",
  "statut" : "en_cours"
}

> {%
    client.test("Create executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### La vue de suivi de l'audit, filtre non audite
GET {{api}}/rest/v1/suivi_audit?select=action_id,statut,ordre_du_jour&collectivite_id=eq.1&referentiel=eq.eci&or=(and(or(statut.in.(non_audite),+statuts.ov.{non_audite})))
apikey: {{anon}}
Authorization: Bearer {{auth_token}}

### La vue de suivi de l'audit, filtre pas à l'ordre du jour
GET {{api}}/rest/v1/suivi_audit?select=action_id,statut,ordre_du_jour&collectivite_id=eq.1&referentiel=eq.eci&or=(and(or(ordre_du_jour.in.(false),+ordres_du_jour.ov.{false})))
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
