### Upsert indicateurs and update indicateur action relationships.
POST {{api}}/rest/v1/rpc/business_upsert_indicateurs
apikey: {{service}}
Authorization: Bearer {{service}}
Content-Type: application/json

{
  "indicateur_definitions": [
    {
      "id": "t_1",
      "indicateur_group": "eci",
      "identifiant": "a",
      "valeur_indicateur": null,
      "nom": "Yo",
      "description": "yo !",
      "unite": "t",
      "obligation_eci": false,
      "parent": null
    },
    {
      "id": "t_2",
      "indicateur_group": "eci",
      "identifiant": "b",
      "valeur_indicateur": null,
      "nom": "Lo",
      "description": "lo !",
      "unite": "kg",
      "obligation_eci": false,
      "parent": null
    }
  ],
  "indicateur_actions": [
    {
      "indicateur_id": "t_1",
      "action_id": "cae_4.1.2"
    },
    {
      "indicateur_id": "t_2",
      "action_id": "cae_4.1.2"
    }
  ]
}

### Get indicateur definition
GET {{api}}/rest/v1/indicateur_definition?id=eq.t_1
apikey: {{service}}
Authorization: Bearer {{service}}
Content-Type: application/json

### Get indicateur action relashionship
GET {{api}}/rest/v1/indicateur_action?indicateur_id=eq.t_1
apikey: {{service}}
Authorization: Bearer {{service}}
Content-Type: application/json

### Update existing action definitions
POST {{api}}/rest/v1/rpc/business_update_actions
apikey: {{service}}
Authorization: Bearer {{service}}
Content-Type: application/json

{
  "definitions": [
    {
      "action_id": "cae",
      "referentiel": "cae",
      "identifiant": "",
      "nom": "Le référentiel répondant au doux nom de CLIMAT AIR ÉNERGIE",
      "description": "",
      "contexte": "",
      "exemples": "",
      "ressources": "",
      "preuve": "",
      "points": null,
      "pourcentage": null
    },
    {
      "action_id": "eci",
      "referentiel": "eci",
      "identifiant": "",
      "nom": "Le référentiel Économie Circulaire qui repose sur 7 piliers. Un par nain, en fait.",
      "description": "",
      "contexte": "",
      "exemples": "",
      "ressources": "",
      "preuve": "des photos",
      "points": null,
      "pourcentage": null
    }
  ],
  "computed_points": [
    {
      "action_id": "cae",
      "value": 50
    },
    {
      "action_id": "eci",
      "value": 5000
    }
  ]
}


### Get action definition
GET {{api}}/rest/v1/action_definition?action_id=eq.eci
apikey: {{service}}
Authorization: Bearer {{service}}
Content-Type: application/json


### Get action computed points
GET {{api}}/rest/v1/action_computed_points?action_id=eq.cae
apikey: {{service}}
Authorization: Bearer {{service}}
Content-Type: application/json



### Upsert personnalisation data
POST {{api}}/rest/v1/rpc/business_upsert_personnalisations
apikey: {{service}}
Authorization: Bearer {{service}}
Content-Type: application/json

{
  "personnalisations": [
    {
      "action_id": "eci_1.1.1",
      "titre": "Yolo !",
      "description": "....",
      "regles": [
        {
          "formule": "yo(lo)",
          "type": "reduction",
          "description": "yolo"
        },
        {
          "formule": "yo(no)",
          "type": "desactivation",
          "description": "yono"
        }
      ]
    }
  ]
}


### Upsert personnalisation data
POST {{api}}/rest/v1/rpc/business_upsert_questions
apikey: {{service}}
Authorization: Bearer {{service}}
Content-Type: application/json


{
  "questions": [
    {
      "id": "question_1",
      "formulation": "Est-ce que la collectivité est compétente en voirie ?",
      "description": "Une petite description",
      "thematique_id": "mobilites",
      "action_ids": [
        "eci_1"
      ],
      "type": "choix",
      "choix": [
        {
          "id": "question_a",
          "formulation": "Oui"
        },
        {
          "id": "question_b",
          "formulation": "Non"
        }
      ]
    }
  ]
}
