### Authenticate as a user
POST {{api}}/auth/v1/token?grant_type=password
apikey: {{anon}}
Content-Type: application/json

{
  "email": "{{yolo_mail}}",
  "password": "{{yolo_pass}}"
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.log('token is ' + response.body['access_token']);
    client.global.set("auth_token", response.body['access_token']);
%}

### List owned collectivite
GET {{api}}/rest/v1/owned_collectivite?select=*
apikey: {{anon}}
Authorization: Bearer {{auth_token}}


### Les collectivités et le niveau d'accès de l'utilisateur
GET {{api}}/rest/v1/collectivite_niveau_acces?select=*
apikey: {{anon}}
Authorization: Bearer {{auth_token}}

### List named collectivite
GET {{api}}/rest/v1/named_collectivite?select=*
apikey: {{anon}}
Authorization: Bearer {{auth_token}}

### List raw epcis (not used directly in client)
GET {{api}}/rest/v1/epci?select=*
apikey: {{anon}}
Authorization: Bearer {{auth_token}}



