### Authenticate as a user
POST {{api}}/auth/v1/token?grant_type=password
apikey: {{anon}}
Content-Type: application/json

{
  "email": "{{yolo_mail}}",
  "password": "{{yolo_pass}}"
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.log('token is ' + response.body['access_token']);
    client.global.set("auth_token", response.body['access_token']);
%}


### Add a registered user.
POST {{api}}/rest/v1/rpc/add_user
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "collectivite_id": 1,
  "email": "yulu@dudu.com",
  "niveau": "lecture"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Add a non-registered user to get an invitation.
POST {{api}}/rest/v1/rpc/add_user
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "collectivite_id": 1,
  "email": "yoyo@nono.no",
  "niveau": "lecture"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.log('invitation id is' + response.body['invitation_id']);
    client.global.set("invitation_id", response.body['invitation_id']);
%}






