
### Generate a recovery link as a service, the link will be sent to the user via mail.
POST {{api}}/auth/v1/admin/generate_link
apikey: {{service}}
Authorization: Bearer {{service}}
Content-Type: application/json

{
  "type": "recovery",
  "email": "yolo@dodo.com"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("recovery_token", response.body['action_link'].match(/token=([A-Z0-9\-\_]+)/i)[1]);
%}

### Consume the recovery as an user.
POST {{api}}/auth/v1/verify
apikey: {{anon}}
Content-Type: application/json

{
  "type": "recovery",
  "token": "{{recovery_token}}"
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body["access_token"], "La réponse ne comporte pas access_token");
        client.assert(response.body["token_type"] === "bearer", "Le token n'est pas un bearer token");
    });
%}
