### Authenticate as a user
POST {{api}}/auth/v1/token?grant_type=password
apikey: {{anon}}
Content-Type: application/json

{
  "email": "{{yolo_mail}}",
  "password": "{{yolo_pass}}"
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.log('token is ' + response.body['access_token']);
    client.global.set("auth_token", response.body['access_token']);
%}

### Insérer un csv
POST {{api}}/rest/v1/fiche_action_import_csv
apikey: {{service}}
Authorization: Bearer {{service}}
Prefer: params=multiple-objects, return=representation, resolution=merge-duplicates
Content-Type: text/csv

< ./test_plan_action.csv