### Authenticate as a user
POST {{api}}/auth/v1/token?grant_type=password
apikey: {{anon}}
Content-Type: application/json

{
  "email": "{{yolo_mail}}",
  "password": "{{yolo_pass}}"
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.log('token is ' + response.body['access_token']);
    client.global.set("auth_token", response.body['access_token']);
%}

### List all plans of collectivite 1
GET {{api}}/rest/v1/plan_action?collectivite_id=eq.1
apikey: {{anon}}
Authorization: Bearer {{auth_token}}


### Upsert a plan
POST {{api}}/rest/v1/plan_action
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
Prefer: return=representation, resolution=merge-duplicates
Content-Type: application/json

{
  "uid": "29770546-f389-4d4f-bfdb-b0c94a1bd0f0",
  "collectivite_id": 1,
  "nom": "Plan d'actions de la collectivité",
  "categories": [
    {
      "nom": "1. Yolo",
      "uid": "ef599348-6ab9-4dc7-bf62-41b9a17ea5fa"
    }
  ],
  "fiches_by_category": [
    {
      "fiche_uid": "17440546-f389-4d4f-bfdb-b0c94a1bd0f9",
      "category_uid": "ef599348-6ab9-4dc7-bf62-41b9a17ea5fa"
    }
  ]
}

### List all fiches of collectivite 1
GET {{api}}/rest/v1/fiche_action?collectivite_id=eq.1
apikey: {{anon}}
Authorization: Bearer {{auth_token}}

> {%
    client.test("List executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Upsert a fiche
POST {{api}}/rest/v1/fiche_action
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
Prefer: return=representation, resolution=merge-duplicates
Content-Type: application/json

{
  "uid": "55640546-f389-4d4f-bfdb-b0c94a1bd0f9",
  "collectivite_id": 1,
  "avancement": "pas_fait",
  "numerotation": "A1",
  "titre": "titre http",
  "description": "description",
  "structure_pilote": "pilote",
  "personne_referente": "référente",
  "elu_referent": "référent",
  "partenaires": "partenaires",
  "budget_global": 150,
  "commentaire": "commentaire",
  "date_fin": "fin",
  "date_debut": "début",
  "en_retard": true,
  "action_ids": [
    "cae"
  ],
  "indicateur_ids": [
    "ind0"
  ],
  "indicateur_personnalise_ids": [
    1
  ]
}

> {%
    client.test("Insert executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}


### Insert a fiche on a collectivité that is not ours
POST {{api}}/rest/v1/fiche_action
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
Prefer: return=representation
Content-Type: application/json

{
  "uid": "55640546-f389-4d4f-bfdb-b0c94a1bd0f9",
  "collectivite_id": 10,
  "avancement": "pas_fait",
  "numerotation": "A1",
  "titre": "titre http",
  "description": "description",
  "structure_pilote": "pilote",
  "personne_referente": "référente",
  "elu_referent": "référent",
  "partenaires": "partenaires",
  "budget_global": 150,
  "commentaire": "commentaire",
  "date_fin": "fin",
  "date_debut": "début",
  "en_retard": true,
  "action_ids": [
    "cae"
  ],
  "indicateur_ids": [
    "ind0"
  ],
  "indicateur_personnalise_ids": [
    1
  ]
}

> {%
    client.test("Insert did not work as expected", function() {
        client.assert(response.status === 403, "Response status is not 403");
    });
%}
