### Authenticate as a user
POST {{api}}/auth/v1/token?grant_type=password
apikey: {{anon}}
Content-Type: application/json

{
  "email": "{{yolo_mail}}",
  "password": "{{yolo_pass}}"
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.log('token is ' + response.body['access_token']);
    client.global.set("auth_token", response.body['access_token']);
%}

### Insérer un csv
POST {{api}}/rest/v1/fiche_action_import_csv
apikey: {{service}}
Authorization: Bearer {{service}}
Prefer: params=multiple-objects, return=representation, resolution=merge-duplicates
Content-Type: text/csv

< ./tpa.csv


### Appeler un plan d'action
POST {{api}}/auth/v1/rpc/plan_action
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{"id" : 1}



### une fiche
GET {{api}}/rest/v1/fiches_action?select=*&id=eq.2760
apikey: {{anon}}
Authorization: Bearer {{auth_token}}

### toute les fiches
GET {{api}}/rest/v1/fiches_action
apikey: {{anon}}
Authorization: Bearer {{auth_token}}

### plan
POST {{api}}/rest/v1/rpc/plan_action
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{"id": 1}

### peut_lire_la_fiche
POST {{api}}/rest/v1/rpc/peut_lire_la_fiche
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{"fiche_id": 6419}

### can_read_acces_restreint
POST {{api}}/rest/v1/rpc/can_read_acces_restreint
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{"collectivite_id": 5460}

### tableau de bord
POST {{api}}/rest/v1/rpc/plan_action_tableau_de_bord
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{"collectivite_id": 1, "plan_id": 12, "sans_plan": false}
