### Authenticate as a user
POST {{api}}/auth/v1/token?grant_type=password
apikey: {{anon}}
Content-Type: application/json

{
  "email": "{{yolo_mail}}",
  "password": "{{yolo_pass}}"
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.log('token is ' + response.body['access_token']);
    client.global.set("auth_token", response.body['access_token']);
%}

### Create a bucket
POST {{api}}/storage/v1/bucket
apikey: {{service}}
Authorization: Bearer {{service}}
Content-Type: application/json

{
  "id": "1",
  "name": "preuves de la collectivité x",
  "public": true
}


### Upload a file
POST {{api}}/storage/v1/object/1f6a5e37-26a4-4f9f-bea8-65ca460113c1/eci_1.1.2/preuve_input.txt
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
x-upsert: true
cacheControl: 3600
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="eci_1.1.2/preuve_input.txt"; filename="eci_1.1.2/preuve_input.txt"

< ./preuve_input.txt
--boundary--

### Download a file
GET {{api}}/storage/v1/object/1f6a5e37-26a4-4f9f-bea8-65ca460113c1/eci_1.1.1/preuve_input.txt
apikey: {{service}}
Authorization: Bearer {{service}}

### List files (does not work with files with slashes)
POST {{api}}/storage/v1/object/list/1f6a5e37-26a4-4f9f-bea8-65ca460113c1
apikey: {{anon}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "prefix": "",
  "limit": 100,
  "offset": 0,
  "sortBy": {
    "column": "name",
    "order": "asc"
  }
}
