### Read user as service
GET {{api}}/rest/v1/rpc/retool_user_list
apikey: {{service}}
Authorization: Bearer {{service}}


### Read users as user
GET {{api}}/rest/v1/rpc/retool_user_list
apikey: {{anon}}
Authorization: Bearer {{auth_token}}


### Update droits as service
PATCH {{api}}/rest/v1/private_utilisateur_droit?id=eq.5
apikey: {{service}}
Authorization: Bearer {{service}}
Prefer: return=representation
Content-Type: application/json

{ "active": false }
