### Read user list as service
GET {{api}}/rest/v1/retool_user_list
apikey: {{service}}
Authorization: Bearer {{service}}


### Read user collectivite list as service
GET {{api}}/rest/v1/retool_user_collectivites_list
apikey: {{service}}
Authorization: Bearer {{service}}


### Read collectivite completude from list as service
GET {{api}}/rest/v1/retool_completude?collectivite_id=eq.5453
apikey: {{service}}
Authorization: Bearer {{service}}


### Read user collectivite computed completude from list as service
GET {{api}}/rest/v1/retool_completude_compute?collectivite_id=eq.5453
apikey: {{service}}
Authorization: Bearer {{service}}


### Read user collectivite computed completude from list as service
GET {{api}}/rest/v1/retool_last_activity?collectivite_id=eq.5453
apikey: {{service}}
Authorization: Bearer {{service}}


### Read user collectivite list as service
GET {{api}}/rest/v1/retool_user_collectivites_list
apikey: {{service}}
Authorization: Bearer {{service}}


### Update droits as service
PATCH {{api}}/rest/v1/private_utilisateur_droit?id=eq.5
apikey: {{service}}
Authorization: Bearer {{service}}
Prefer: return=representation
Content-Type: application/json

{ "active": false }


### Read score as service
GET {{api}}/rest/v1/retool_score?collectivite_id=eq.2765&referentiel=eq.eci
apikey: {{service}}
Authorization: Bearer {{service}}
