### La progression nationale
GET {{api}}/rest/v1/stats_locales_evolution_total_activation?select=*&code_departement=is.null&code_region=is.null
apikey: {{anon}}

### La completude par tranche
GET {{api}}/rest/v1/stats_locales_tranche_completude?code_departement=is.null&code_region=is.null
apikey: {{anon}}

### Le comptage des collectivités avec des étoiles dans l'Ain
GET {{api}}/rest/v1/stats_locales_engagement_collectivite?and=(or(etoiles_eci.gte.1,etoiles_cae.gte.1),code_departement.eq.01)
apikey: {{anon}}
Content-Type: application/json
Prefer: count=exact

### Le comptage des COT
GET {{api}}/rest/v1/cot?actif=is.true
apikey: {{anon}}
Content-Type: application/json
Prefer: count=exact
